"""Deep and shallow Lean emitters (pure AST -> str, ``pretty.py``-shaped).

Deep: the program as a term of the ``Ttac`` inductive types, registers
by number, blocks by index. Shallow: per-block ``Prop`` defs in
Boogie/wp style over the source names.

All Lean constructor spellings live in ``_DEEP`` so a library rename is
a one-line diff here.
"""

from __future__ import annotations

import networkx as nx

from ctac.ttac import ast
from ctac.ttac.analysis import cfg
from ctac.ttac.ast import Ty

from .liveness import BlockLiveness
from .naming import Numbering, ShallowNames

_DEEP = {
    "litI": ".litI",
    "litB": ".litB",
    "varI": ".var .int",
    "varB": ".var .bool",
    "+": ".add",
    "-": ".sub",
    "*": ".mul",
    "/": ".div",
    "<=": ".le",
    "<": ".lt",
    "eqI": ".eqI",
    "eqB": ".eqB",
    "not": ".not",
    "and": ".and",
    "or": ".or",
    "ite": ".ite",
    "assignI": ".assign .int",
    "assignB": ".assign .bool",
    "havocI": ".havoc .int",
    "havocB": ".havoc .bool",
    "phiI": ".phi .int",
    "phiB": ".phi .bool",
    "varM": ".var .map",
    "select": ".select",
    "store": ".store",
    "assignM": ".assign .map",
    "havocM": ".havoc .map",
    "phiM": ".phi .map",
    "assume": ".assume",
    "assert": ".assert",
    "halt": ".halt",
    "goto": ".goto",
    "ifGoto": ".ifGoto",
}

_GENERATED_HEADER = "/- Generated by `{tool}`{source}. DO NOT EDIT. -/"


def _header(source: str | None, *, tool: str = "ttac lean") -> str:
    return _GENERATED_HEADER.format(
        tool=tool, source=f" from {source}" if source else ""
    )


def expr_ty(e: ast.Expr, types: dict[str, Ty]) -> Ty:
    """Structural expression type (input is validated)."""
    if isinstance(e, ast.Num):
        return Ty.INT
    if isinstance(e, ast.BoolLit):
        return Ty.BOOL
    if isinstance(e, ast.Var):
        return types[e.name]
    if isinstance(e, ast.Load):
        return Ty.INT
    if isinstance(e, ast.Update):
        return Ty.BYTEMAP
    if isinstance(e, ast.BinExpr):
        if e.op in ("+", "-", "*", "/"):
            return Ty.INT
        return Ty.BOOL
    if isinstance(e, ast.UnExpr):
        return Ty.BOOL
    if isinstance(e, ast.IfExpr):
        return expr_ty(e.then, types)
    raise TypeError(f"unsupported expression node {type(e).__name__}")


def _nat_lit(n: int) -> str:
    return str(n) if n >= 0 else f"({n})"


# --- deep emitter ---


def deep_mexpr(e: ast.Expr, num: Numbering, types: dict[str, Ty]) -> str:
    if isinstance(e, ast.Var):
        return f"({_DEEP['varM']} {num.map_regs[e.name]})"
    if isinstance(e, ast.Update):
        base = deep_mexpr(e.base, num, types)
        idx = deep_iexpr(e.index, num, types)
        val = deep_iexpr(e.value, num, types)
        return f"({_DEEP['store']} {base} {idx} {val})"
    raise TypeError(f"unsupported map expression {type(e).__name__}")


def deep_iexpr(e: ast.Expr, num: Numbering, types: dict[str, Ty]) -> str:
    if isinstance(e, ast.Num):
        return f"({_DEEP['litI']} {_nat_lit(e.value)})"
    if isinstance(e, ast.Var):
        return f"({_DEEP['varI']} {num.int_regs[e.name]})"
    if isinstance(e, ast.Load):
        base = deep_mexpr(e.base, num, types)
        idx = deep_iexpr(e.index, num, types)
        return f"({_DEEP['select']} {base} {idx})"
    if isinstance(e, ast.BinExpr):
        lhs = deep_iexpr(e.lhs, num, types)
        rhs = deep_iexpr(e.rhs, num, types)
        return f"({_DEEP[e.op]} {lhs} {rhs})"
    if isinstance(e, ast.IfExpr):
        cond = deep_bexpr(e.cond, num, types)
        then = deep_iexpr(e.then, num, types)
        els = deep_iexpr(e.els, num, types)
        return f"({_DEEP['ite']} {cond} {then} {els})"
    raise TypeError(f"unsupported int expression {type(e).__name__}")


def deep_bexpr(e: ast.Expr, num: Numbering, types: dict[str, Ty]) -> str:
    if isinstance(e, ast.BoolLit):
        return f"({_DEEP['litB']} {'true' if e.value else 'false'})"
    if isinstance(e, ast.Var):
        return f"({_DEEP['varB']} {num.bool_regs[e.name]})"
    if isinstance(e, ast.UnExpr):
        return f"({_DEEP['not']} {deep_bexpr(e.operand, num, types)})"
    if isinstance(e, ast.BinExpr):
        if e.op in ("<=", "<"):
            lhs = deep_iexpr(e.lhs, num, types)
            rhs = deep_iexpr(e.rhs, num, types)
            return f"({_DEEP[e.op]} {lhs} {rhs})"
        if e.op == "==":
            if expr_ty(e.lhs, types) is Ty.INT:
                lhs = deep_iexpr(e.lhs, num, types)
                rhs = deep_iexpr(e.rhs, num, types)
                return f"({_DEEP['eqI']} {lhs} {rhs})"
            lhs = deep_bexpr(e.lhs, num, types)
            rhs = deep_bexpr(e.rhs, num, types)
            return f"({_DEEP['eqB']} {lhs} {rhs})"
        lhs = deep_bexpr(e.lhs, num, types)
        rhs = deep_bexpr(e.rhs, num, types)
        return f"({_DEEP[e.op]} {lhs} {rhs})"
    if isinstance(e, ast.IfExpr):
        cond = deep_bexpr(e.cond, num, types)
        then = deep_bexpr(e.then, num, types)
        els = deep_bexpr(e.els, num, types)
        return f"({_DEEP['ite']} {cond} {then} {els})"
    raise TypeError(f"unsupported bool expression {type(e).__name__}")


def deep_cmd(c: ast.Cmd, num: Numbering, types: dict[str, Ty]) -> str:
    if isinstance(c, ast.Assign):
        ty = types[c.target.name]
        if ty is Ty.INT:
            return f"{_DEEP['assignI']} {num.int_regs[c.target.name]} " \
                   f"{deep_iexpr(c.rhs, num, types)}"
        if ty is Ty.BOOL:
            return f"{_DEEP['assignB']} {num.bool_regs[c.target.name]} " \
                   f"{deep_bexpr(c.rhs, num, types)}"
        return f"{_DEEP['assignM']} {num.map_regs[c.target.name]} " \
               f"{deep_mexpr(c.rhs, num, types)}"
    if isinstance(c, ast.Havoc):
        ty = types[c.target.name]
        if ty is Ty.INT:
            return f"{_DEEP['havocI']} {num.int_regs[c.target.name]}"
        if ty is Ty.BOOL:
            return f"{_DEEP['havocB']} {num.bool_regs[c.target.name]}"
        return f"{_DEEP['havocM']} {num.map_regs[c.target.name]}"
    if isinstance(c, ast.Phi):
        ty = types[c.target.name]
        regs, ctor = {
            Ty.INT: (num.int_regs, _DEEP["phiI"]),
            Ty.BOOL: (num.bool_regs, _DEEP["phiB"]),
            Ty.BYTEMAP: (num.map_regs, _DEEP["phiM"]),
        }[ty]
        arms = ", ".join(
            f"({num.block_index[a.label]}, {regs[a.value]})" for a in c.arms
        )
        target = regs[c.target.name]
        return f"{ctor} {target} [{arms}]"
    if isinstance(c, ast.Assume):
        return f"{_DEEP['assume']} {deep_bexpr(c.cond, num, types)}"
    if isinstance(c, ast.Assert):
        return f"{_DEEP['assert']} {num.bool_regs[c.cond_name]}"
    raise TypeError(f"unsupported command {type(c).__name__}")


def deep_terminator(t: ast.Terminator, num: Numbering) -> str:
    if isinstance(t, ast.Halt):
        return _DEEP["halt"]
    if isinstance(t, ast.Goto):
        return f"{_DEEP['goto']} {num.block_index[t.target]}"
    if isinstance(t, ast.IfGoto):
        return (
            f"{_DEEP['ifGoto']} {num.bool_regs[t.cond]} "
            f"{num.block_index[t.then_target]} {num.block_index[t.else_target]}"
        )
    raise TypeError(f"unsupported terminator {type(t).__name__}")


def _name_map_comment(num: Numbering) -> list[str]:
    def row(regs: dict[str, int]) -> str:
        if not regs:
            return "(none)"
        return ", ".join(f"{i} = {n}" for n, i in sorted(regs.items(), key=lambda kv: kv[1]))

    lines = [
        "/-!",
        f"int registers:  {row(num.int_regs)}",
        f"bool registers: {row(num.bool_regs)}",
    ]
    if num.map_regs:
        lines.append(f"map registers:  {row(num.map_regs)}")
    lines.extend([
        f"blocks:         {row(num.block_index)}",
        "-/",
    ])
    return lines


def deep_module(
    program: ast.Program,
    num: Numbering,
    types: dict[str, Ty],
    module_name: str,
    source: str | None = None,
    *,
    tool: str = "ttac lean",
) -> str:
    lines = [
        _header(source, tool=tool),
        "import Ttac",
        "",
        f"namespace {module_name}.Deep",
        "",
        "open Ttac",
        "",
        *_name_map_comment(num),
        "",
        "def prog : Program where",
        "  blocks := [",
    ]
    block_texts = []
    for block in program.blocks:
        idx = num.block_index[block.label]
        term = deep_terminator(block.terminator, num)
        if block.commands:
            cmds = ",\n        ".join(deep_cmd(c, num, types) for c in block.commands)
            block_texts.append(
                f"    -- {idx}: {block.label}\n"
                f"    {{ cmds := [\n        {cmds}],\n"
                f"      term := {term} }}"
            )
        else:
            block_texts.append(
                f"    -- {idx}: {block.label}\n"
                f"    {{ cmds := [], term := {term} }}"
            )
    lines.append(",\n".join(block_texts) + "]")
    lines.append(f"  entry := {num.entry_index}")
    if program.exit is not None:
        lines.append(f"  exit := some {num.block_index[program.exit]}")
    else:
        lines.append("  exit := none")
    lines.extend(["", f"end {module_name}.Deep", ""])
    return "\n".join(lines)


# --- shallow emitter ---


def _is_atom(e: ast.Expr) -> bool:
    return isinstance(e, ast.Var) or isinstance(e, ast.BoolLit) or (
        isinstance(e, ast.Num) and e.value >= 0
    )


def shallow_iexpr(e: ast.Expr, names: ShallowNames, types: dict[str, Ty]) -> str:
    if isinstance(e, ast.Num):
        return str(e.value)
    if isinstance(e, ast.Var):
        return names.regs[e.name]
    if isinstance(e, ast.BinExpr):
        lhs = _wrap_i(e.lhs, names, types)
        rhs = _wrap_i(e.rhs, names, types)
        if e.op == "/":
            return f"Int.ediv {lhs} {rhs}"
        return f"{lhs} {e.op} {rhs}"
    if isinstance(e, ast.IfExpr):
        cond = shallow_bexpr(e.cond, names, types)
        then = shallow_iexpr(e.then, names, types)
        els = shallow_iexpr(e.els, names, types)
        return f"if {cond} then {then} else {els}"
    raise TypeError(f"unsupported int expression {type(e).__name__}")


def shallow_bexpr(e: ast.Expr, names: ShallowNames, types: dict[str, Ty]) -> str:
    if isinstance(e, ast.BoolLit):
        return "true" if e.value else "false"
    if isinstance(e, ast.Var):
        return names.regs[e.name]
    if isinstance(e, ast.UnExpr):
        return f"!{_wrap_b(e.operand, names, types)}"
    if isinstance(e, ast.BinExpr):
        if e.op in ("<=", "<"):
            op = "≤" if e.op == "<=" else "<"
            lhs = shallow_iexpr(e.lhs, names, types)
            rhs = shallow_iexpr(e.rhs, names, types)
            return f"decide ({lhs} {op} {rhs})"
        if e.op == "==":
            if expr_ty(e.lhs, types) is Ty.INT:
                lhs = shallow_iexpr(e.lhs, names, types)
                rhs = shallow_iexpr(e.rhs, names, types)
                return f"decide ({lhs} = {rhs})"
            lhs = _wrap_b(e.lhs, names, types)
            rhs = _wrap_b(e.rhs, names, types)
            return f"{lhs} == {rhs}"
        op = "&&" if e.op == "and" else "||"
        lhs = _wrap_b(e.lhs, names, types)
        rhs = _wrap_b(e.rhs, names, types)
        return f"{lhs} {op} {rhs}"
    if isinstance(e, ast.IfExpr):
        cond = shallow_bexpr(e.cond, names, types)
        then = shallow_bexpr(e.then, names, types)
        els = shallow_bexpr(e.els, names, types)
        return f"if {cond} then {then} else {els}"
    raise TypeError(f"unsupported bool expression {type(e).__name__}")


def _wrap_i(e: ast.Expr, names: ShallowNames, types: dict[str, Ty]) -> str:
    s = shallow_iexpr(e, names, types)
    return s if _is_atom(e) else f"({s})"


def _wrap_b(e: ast.Expr, names: ShallowNames, types: dict[str, Ty]) -> str:
    s = shallow_bexpr(e, names, types)
    return s if _is_atom(e) else f"({s})"


def _ty_str(ty: Ty) -> str:
    return "Int" if ty is Ty.INT else "Bool"


def _call_str(
    pred_label: str,
    succ_label: str,
    program: ast.Program,
    params_of: dict[str, tuple[str, ...]],
    names: ShallowNames,
) -> str:
    by_label = {b.label: b for b in program.blocks}
    phi_by_target = {
        c.target.name: c
        for c in by_label[succ_label].commands
        if isinstance(c, ast.Phi)
    }
    args = []
    for param in params_of[succ_label]:
        phi = phi_by_target.get(param)
        if phi is not None:
            arm = next(a for a in phi.arms if a.label == pred_label)
            args.append(names.regs[arm.value])
        else:
            args.append(names.regs[param])
    call = names.block_defs[succ_label]
    return " ".join([call, *args])


def _shallow_body(
    block: ast.Block,
    program: ast.Program,
    params_of: dict[str, tuple[str, ...]],
    names: ShallowNames,
    types: dict[str, Ty],
    prefix: tuple[str, ...] = (),
) -> list[str]:
    term = block.terminator
    if isinstance(term, ast.Halt):
        lines = ["True"]
    elif isinstance(term, ast.Goto):
        lines = [_call_str(block.label, term.target, program, params_of, names)]
    elif isinstance(term, ast.IfGoto):
        cond = names.regs[term.cond]
        then_call = _call_str(block.label, term.then_target, program, params_of, names)
        else_call = _call_str(block.label, term.else_target, program, params_of, names)
        lines = [f"({cond} = true → {then_call}) ∧ ({cond} = false → {else_call})"]
    else:
        raise TypeError(f"unsupported terminator {type(term).__name__}")
    # Nested child block-defs are part of the continuation: they sit after
    # every command of this block (they may read its lets) and before the
    # terminator Prop, so an assert wrap correctly parenthesizes them in.
    lines = [*prefix, *lines]

    for cmd in reversed(block.commands):
        if isinstance(cmd, ast.Phi):
            continue  # phi targets are block parameters
        if isinstance(cmd, ast.Havoc):
            name = names.regs[cmd.target.name]
            lines = [f"∀ ({name} : {_ty_str(types[cmd.target.name])}),", *lines]
        elif isinstance(cmd, ast.Assign):
            name = names.regs[cmd.target.name]
            ty = types[cmd.target.name]
            rhs = (
                shallow_iexpr(cmd.rhs, names, types)
                if ty is Ty.INT
                else shallow_bexpr(cmd.rhs, names, types)
            )
            lines = [f"let {name} : {_ty_str(ty)} := {rhs}", *lines]
        elif isinstance(cmd, ast.Assume):
            lines = [f"{_wrap_b(cmd.cond, names, types)} = true →", *lines]
        elif isinstance(cmd, ast.Assert):
            cond = names.regs[cmd.cond_name]
            # `∧` binds tighter than `→`, so a continuation containing a
            # top-level implication must be parenthesized.
            if len(lines) == 1 and "→" not in lines[0]:
                lines = [f"{cond} = true ∧ {lines[0]}"]
            else:
                lines = [f"{cond} = true ∧", f"({lines[0]}", *lines[1:-1], f"{lines[-1]})"]
        else:
            raise TypeError(f"unsupported command {type(cmd).__name__}")
    return lines


def _dominator_children(program: ast.Program) -> dict[str, list[str]]:
    """Dominator-tree children per block, reverse-topologically ordered.

    Reverse topological sibling order puts every join before its
    predecessors, so a `let rec` block-def is always in scope at its
    call sites (a join's idom dominates all the join's predecessors).
    """
    graph = cfg.to_digraph(program)
    idom = nx.immediate_dominators(graph, program.entry)
    pos = {label: i for i, label in enumerate(cfg.topo_order(program))}
    children: dict[str, list[str]] = {b.label: [] for b in program.blocks}
    for label, dom in idom.items():
        if label != program.entry:
            children[dom].append(label)
    for kids in children.values():
        kids.sort(key=lambda lb: pos[lb], reverse=True)
    return children


def _nested_block_lines(
    label: str,
    program: ast.Program,
    by_label: dict[str, ast.Block],
    children: dict[str, list[str]],
    live: BlockLiveness,
    names: ShallowNames,
    types: dict[str, Ty],
) -> list[str]:
    params = " ".join(
        f"({names.regs[p]} : {_ty_str(types[p])})" for p in live.phi_targets[label]
    )
    head = f"let rec {names.block_defs[label]}{' ' + params if params else ''} : Prop :="
    prefix = tuple(
        ln
        for child in children[label]
        for ln in _nested_block_lines(
            child, program, by_label, children, live, names, types
        )
    )
    body = _shallow_body(
        by_label[label], program, live.phi_targets, names, types, prefix=prefix
    )
    return [head, *(f"  {ln}" for ln in body)]


def shallow_module(
    program: ast.Program,
    num: Numbering,
    types: dict[str, Ty],
    live: BlockLiveness,
    names: ShallowNames,
    module_name: str,
    source: str | None = None,
    *,
    nested: bool = False,
) -> str:
    by_label = {b.label: b for b in program.blocks}
    lines = [
        _header(source),
        "",
        f"namespace {module_name}.Shallow",
        "",
        "/-!",
    ]
    if nested:
        lines.extend([
            "Blocks nested by immediate dominator (`let rec`); parameters are",
            "phi targets only - live-ins are captured lexically. Each",
            '`ok_<label>` states "execution from the top of <label> never',
            'fails an assert".',
            "-/",
        ])
        assert program.entry is not None
        children = _dominator_children(program)
        entry = by_label[program.entry]
        prefix = tuple(
            ln
            for child in children[program.entry]
            for ln in _nested_block_lines(
                child, program, by_label, children, live, names, types
            )
        )
        body = _shallow_body(
            entry, program, live.phi_targets, names, types, prefix=prefix
        )
        lines.extend(["", f"def {names.block_defs[program.entry]} : Prop :="])
        lines.extend(f"  {ln}" for ln in body)
    else:
        lines.extend([
            "Blocks in reverse topological order; each `ok_<label>` states",
            '"execution from the top of <label> never fails an assert".',
            "-/",
        ])
        for label in reversed(cfg.topo_order(program)):
            block = by_label[label]
            params = " ".join(
                f"({names.regs[p]} : {_ty_str(types[p])})" for p in live.params[label]
            )
            sig = f"def {names.block_defs[label]}{' ' + params if params else ''} : Prop :="
            lines.extend(["", sig])
            lines.extend(
                f"  {ln}"
                for ln in _shallow_body(block, program, live.params, names, types)
            )
    lines.extend(["", f"end {module_name}.Shallow", ""])
    return "\n".join(lines)


# --- proofs and root modules ---


def proofs_module(
    program: ast.Program,
    names: ShallowNames,
    module_name: str,
    *,
    deep: bool = True,
    shallow: bool = True,
) -> str:
    assert program.entry is not None
    entry_def = names.block_defs[program.entry]
    lines = []
    if deep:
        lines.append(f"import {module_name}.Deep")
    if shallow:
        lines.append(f"import {module_name}.Shallow")
    lines.extend([
        "",
        "/-!",
        f"Proof obligations for `{module_name}`. Generated once and never",
        "overwritten - proofs written here survive regeneration.",
        "-/",
        "",
        f"namespace {module_name}",
    ])
    if shallow:
        lines.extend([
            "",
            "/-- Shallow safety: no execution from the entry block fails an assert. -/",
            f"theorem shallow_safe : Shallow.{entry_def} := by",
            "  sorry",
        ])
    if deep:
        lines.extend([
            "",
            "/-- Deep safety over the `Ttac` small-step semantics. -/",
            "theorem deep_safe : Deep.prog.Safe := by",
            "  sorry",
        ])
    lines.extend(["", f"end {module_name}", ""])
    return "\n".join(lines)


def root_module(module_name: str, *, deep: bool = True, shallow: bool = True) -> str:
    lines = []
    if deep:
        lines.append(f"import {module_name}.Deep")
    if shallow:
        lines.append(f"import {module_name}.Shallow")
    lines.extend([f"import {module_name}.Proofs", ""])
    return "\n".join(lines)
