"""Driver for ``ttac vc-check``: validate, transpile, emit Lean texts.

The generated project proves ``Ttac.checkVC prog vc = true``;
`lake build` success is the validation verdict. Everything here is
untrusted - the Lean checker re-verifies every property it relies on.
"""

from __future__ import annotations

from dataclasses import dataclass

from ctac.solver.smt2 import parse as parse_smt2
from ctac.ttac import ast
from ctac.ttac.analysis import cfg
from ctac.ttac.errors import VcCheckError

from . import emit
from .encode import validate_for_lean
from .naming import Numbering, build_numbering
from .vc import VcAssert, VcMapDef, build_vc_symbols, render_top, transpile_vc
from .vc_expected import (
    VcMismatch,
    expected_buckets,
    expected_map_defs,
    expected_vc,
    precheck_diff,
)


@dataclass(frozen=True)
class VcCheckResult:
    module_name: str
    deep_text: str
    vc_text: str
    check_text: str
    root_text: str
    numbering: Numbering
    n_asserts: int
    mismatches: tuple[VcMismatch, ...]


def _program_errors(program: ast.Program) -> list[str]:
    errors: list[str] = []
    sites = [
        (b.label, i, len(b.commands))
        for b in program.blocks
        for i, c in enumerate(b.commands)
        if isinstance(c, ast.Assert)
    ]
    if not sites:
        errors.append("program has no assert; nothing to validate")
    elif len(sites) > 1:
        errors.append(
            f"program has {len(sites)} asserts; vc-check requires exactly "
            "one (run `ttac ua --strategy merge` first)"
        )
    elif sites[0][1] + 1 != sites[0][2]:
        errors.append(
            f"assert in block '{sites[0][0]}' is not the last command of "
            "its block"
        )

    idx = {b.label: i for i, b in enumerate(program.blocks)}
    for block in program.blocks:
        for succ in cfg.successors(block):
            if succ in idx and idx[succ] <= idx[block.label]:
                errors.append(
                    f"backward edge {block.label} -> {succ}: vc-check "
                    "requires blocks in topological source order"
                )

    if program.entry is not None:
        preds = cfg.predecessors(program).get(program.entry, [])
        if preds:
            errors.append(
                f"entry block '{program.entry}' has incoming edges "
                f"({', '.join(sorted(preds))})"
            )
        graph = cfg.to_digraph(program)
        import networkx as nx

        reachable = {program.entry} | nx.descendants(graph, program.entry)
        for block in program.blocks:
            if block.label not in reachable:
                errors.append(
                    f"block '{block.label}' is unreachable from entry"
                )
    return errors


def _vc_module(
    constraint_lines: list[str],
    map_def_lines: list[str],
    module_name: str,
    numbering: Numbering,
    smt_source: str | None,
) -> str:
    n_blocks = len(numbering.block_index)
    block_map = ", ".join(
        f".blk {i} = {label}"
        for label, i in sorted(numbering.block_index.items(), key=lambda kv: kv[1])
    )
    if map_def_lines:
        map_defs = ["  mapDefs := [", *map_def_lines]
    else:
        map_defs = ["  mapDefs := []"]
    lines = [
        emit._header(smt_source, tool="ttac vc-check"),
        "import Ttac",
        "",
        f"namespace {module_name}.Vc",
        "",
        "open Ttac",
        "",
        "/-!",
        f"guard atoms: {block_map}; .blk {n_blocks} = BLK_EXIT",
        "-/",
        "",
        "def vc : Ttac.Vc.VC where",
        "  constraints := [",
        *constraint_lines,
        *map_defs,
        "",
        f"end {module_name}.Vc",
        "",
    ]
    return "\n".join(lines)


def _check_module(module_name: str, kernel: bool) -> str:
    tactic = "decide" if kernel else "native_decide"
    trust = (
        "kernel-checked (`decide`)"
        if kernel
        else "proved by `native_decide` (trusts the Lean compiler via the "
        "`Lean.ofReduceBool` axiom)"
    )
    return "\n".join([
        f"/- Generated by `ttac vc-check`. DO NOT EDIT. `vc_ok` is {trust}. -/",
        f"import {module_name}.Deep",
        f"import {module_name}.Vc",
        "",
        f"namespace {module_name}",
        "",
        "/-- The transpiled smt2 asserts all belong to the constraint set the",
        "bwd0 encoder is entitled to emit for the deep program. -/",
        "theorem vc_ok : Ttac.checkVC Deep.prog Vc.vc = true := by",
        f"  {tactic}",
        "",
        "/-- The solver's `unsat` verdict on the smt2 file is `Ttac.Vc.Unsat",
        "Vc.vc` modulo the (goldens-tested) transpilation; under that premise",
        "the program is safe, by the denotational `checkVC_safe_via_denot`. -/",
        "theorem vc_implies_safe : Ttac.Vc.Unsat Vc.vc → Deep.prog.Safe :=",
        "  Ttac.checkVC_safe_via_denot vc_ok",
        "",
        f"end {module_name}",
        "",
    ])


def generate_vc_check(
    program: ast.Program,
    smt2_source: str,
    *,
    module_name: str,
    source: str | None = None,
    smt_source: str | None = None,
    precheck: bool = True,
    kernel: bool = False,
) -> VcCheckResult:
    pre = validate_for_lean(program, maps=True)
    errors = list(pre.errors) + _program_errors(program)
    if errors:
        raise VcCheckError(tuple(errors))

    numbering = build_numbering(program, pre.types)

    smt = parse_smt2(smt2_source)
    syms, sym_errors = build_vc_symbols(program, numbering, pre.types, smt)
    asserts, map_defs, transpile_errors = transpile_vc(smt, syms)
    smt_errors = sym_errors + transpile_errors
    if smt_errors:
        raise VcCheckError(tuple(smt_errors))

    mismatches: tuple[VcMismatch, ...] = ()
    if precheck:
        expected = expected_vc(program, numbering, pre.types)
        expected_defs = expected_map_defs(program, numbering, pre.types)
        mismatches = precheck_diff(asserts, expected, map_defs, expected_defs)

    vc_lines = _render_vc_entries(asserts)
    map_def_lines = _render_map_def_entries(map_defs)
    return VcCheckResult(
        module_name=module_name,
        deep_text=emit.deep_module(
            program, numbering, pre.types, module_name, source,
            tool="ttac vc-check",
        ),
        vc_text=_vc_module(
            vc_lines, map_def_lines, module_name, numbering, smt_source
        ),
        check_text=_check_module(module_name, kernel),
        root_text="\n".join([
            f"import {module_name}.Deep",
            f"import {module_name}.Vc",
            f"import {module_name}.Check",
            "",
        ]),
        numbering=numbering,
        n_asserts=len(asserts),
        mismatches=mismatches,
    )


def _render_vc_entries(asserts: list[VcAssert]) -> list[str]:
    lines: list[str] = []
    last = len(asserts) - 1
    for i, a in enumerate(asserts):
        lines.append(f"    -- line {a.line}: {a.source}")
        sep = "]" if i == last else ","
        lines.append(f"    {render_top(a.term)}{sep}")
    return lines


def _render_map_def_entries(map_defs: list[VcMapDef]) -> list[str]:
    lines: list[str] = []
    last = len(map_defs) - 1
    for i, md in enumerate(map_defs):
        lines.append(f"    -- line {md.line}: {md.source}")
        sep = "]" if i == last else ","
        lines.append(f"    ({md.target}, {render_top(md.term)}){sep}")
    return lines


# ------------------------------------------------------------------------
# Annotated vc-check: the denotational pipeline (Ttac.Vc.AnnVC / checkVCWAnn).
#
# The transpiled smt2 asserts are the same as the flat path; the annotator
# just *files* each one into the bucket (block CFG, a block's commands, or
# the objective) whose generator contains it. The bucketing is untrusted:
# the Lean `checkVCWAnn` re-checks per site that each constraint weakens
# from one of the tagged site's own anchors (membership = the reflexivity
# row of the weakening table, so generator-verbatim filing passes). A
# constraint vcgen has simplified past the filing rule below would need
# weakening-aware filing here; today's output is generator-verbatim.
# ------------------------------------------------------------------------


@dataclass(frozen=True)
class AnnVcCheckResult:
    module_name: str
    deep_text: str
    vc_text: str
    check_text: str
    root_text: str
    numbering: Numbering
    n_asserts: int
    unmatched: tuple[VcAssert, ...]


def _bucket_asserts(
    asserts: list[VcAssert],
    cfg_pb: list[list],
    cmd_pb: list[list],
    objective: list,
) -> tuple[list[list[VcAssert]], list[list[VcAssert]], list[VcAssert], list[VcAssert]]:
    n = len(cfg_pb)
    cfg_b: list[list[VcAssert]] = [[] for _ in range(n)]
    cmd_b: list[list[VcAssert]] = [[] for _ in range(n)]
    obj: list[VcAssert] = []
    unmatched: list[VcAssert] = []
    cfg_sets = [set(x) for x in cfg_pb]
    cmd_sets = [set(x) for x in cmd_pb]
    obj_set = set(objective)
    for a in asserts:
        for b in range(n):
            if a.term in cfg_sets[b]:
                cfg_b[b].append(a)
                break
        else:
            for b in range(n):
                if a.term in cmd_sets[b]:
                    cmd_b[b].append(a)
                    break
            else:
                if a.term in obj_set:
                    obj.append(a)
                else:
                    unmatched.append(a)
    return cfg_b, cmd_b, obj, unmatched


def _bucket_terms(asserts: list[VcAssert]) -> str:
    return "[" + ", ".join(render_top(a.term) for a in asserts) + "]"


def _ann_vc_module(
    cfg_b: list[list[VcAssert]],
    cmd_b: list[list[VcAssert]],
    obj: list[VcAssert],
    map_defs: list[VcMapDef],
    module_name: str,
    numbering: Numbering,
    smt_source: str | None,
) -> str:
    block_lines: list[str] = []
    for b in range(len(cfg_b)):
        label = next(
            (lbl for lbl, i in numbering.block_index.items() if i == b), str(b)
        )
        sep = "," if b + 1 < len(cfg_b) else ""
        block_lines.append(f"    -- block {b} ({label})")
        block_lines.append(
            f"    {{ cfg := {_bucket_terms(cfg_b[b])},"
        )
        block_lines.append(
            f"      cmds := [{_bucket_terms(cmd_b[b])}] }}{sep}"
        )
    if map_defs:
        map_lines = ["  mapDefs := [", *_render_map_def_entries(map_defs)]
    else:
        map_lines = ["  mapDefs := []"]
    lines = [
        emit._header(smt_source, tool="ttac ann-vc-check"),
        "import Ttac",
        "",
        f"namespace {module_name}.Vc",
        "",
        "open Ttac",
        "",
        "def vc : Ttac.Vc.AnnVC where",
        "  perBlock := [",
        *block_lines,
        "  ]",
        f"  objective := {_bucket_terms(obj)}",
        *map_lines,
        "",
        f"end {module_name}.Vc",
        "",
    ]
    return "\n".join(lines)


def _ann_check_module(module_name: str, kernel: bool) -> str:
    tactic = "decide" if kernel else "native_decide"
    return "\n".join([
        "/- Generated by `ttac ann-vc-check`. DO NOT EDIT. -/",
        f"import {module_name}.Deep",
        f"import {module_name}.Vc",
        "",
        f"namespace {module_name}",
        "",
        "/-- Every bucket constraint weakens from one of its own site's",
        "anchors (the weakening-table admission, validated per site; the",
        "global expected VC is never computed). -/",
        "theorem vc_ok : Ttac.checkVCWAnn Deep.prog Vc.vc = true := by",
        f"  {tactic}",
        "",
        "/-- The solver's `unsat` verdict on the smt2 file is",
        "`Ttac.Vc.AnnVC.Unsat Vc.vc` modulo the transpilation; under that",
        "premise the program is safe, by the denotational route",
        "(`checkVCWAnn_safe`: adequacy + weak-enough admission). -/",
        "theorem vc_implies_safe : Ttac.Vc.AnnVC.Unsat Vc.vc → Deep.prog.Safe :=",
        "  Ttac.checkVCWAnn_safe vc_ok",
        "",
        f"end {module_name}",
        "",
    ])


def generate_ann_vc_check(
    program: ast.Program,
    smt2_source: str,
    *,
    module_name: str,
    source: str | None = None,
    smt_source: str | None = None,
    kernel: bool = False,
) -> AnnVcCheckResult:
    pre = validate_for_lean(program, maps=True)
    errors = list(pre.errors) + _program_errors(program)
    if errors:
        raise VcCheckError(tuple(errors))

    numbering = build_numbering(program, pre.types)
    smt = parse_smt2(smt2_source)
    syms, sym_errors = build_vc_symbols(program, numbering, pre.types, smt)
    asserts, map_defs, transpile_errors = transpile_vc(smt, syms)
    smt_errors = sym_errors + transpile_errors
    if smt_errors:
        raise VcCheckError(tuple(smt_errors))

    cfg_pb, cmd_pb, objective = expected_buckets(program, numbering, pre.types)
    cfg_b, cmd_b, obj, unmatched = _bucket_asserts(
        asserts, cfg_pb, cmd_pb, objective
    )
    if unmatched:
        raise VcCheckError(tuple(
            f"assert not in any block generator (line {a.line}): {a.source}"
            for a in unmatched
        ))

    return AnnVcCheckResult(
        module_name=module_name,
        deep_text=emit.deep_module(
            program, numbering, pre.types, module_name, source,
            tool="ttac ann-vc-check",
        ),
        vc_text=_ann_vc_module(
            cfg_b, cmd_b, obj, map_defs, module_name, numbering, smt_source
        ),
        check_text=_ann_check_module(module_name, kernel),
        root_text="\n".join([
            f"import {module_name}.Deep",
            f"import {module_name}.Vc",
            f"import {module_name}.Check",
            "",
        ]),
        numbering=numbering,
        n_asserts=len(asserts),
        unmatched=tuple(unmatched),
    )
