"""Driver for ``ttac vc-check``: validate, transpile, emit Lean texts.

The generated project proves ``Ttac.checkVC prog vc = true``;
`lake build` success is the validation verdict. Everything here is
untrusted - the Lean checker re-verifies every property it relies on.
"""

from __future__ import annotations

from dataclasses import dataclass

from ctac.solver.smt2 import parse as parse_smt2
from ctac.ttac import ast
from ctac.ttac.analysis import cfg
from ctac.ttac.errors import VcCheckError

from . import emit
from .encode import validate_for_lean
from .naming import Numbering, build_numbering
from .vc import VcAssert, build_vc_symbols, render_top, transpile_vc
from .vc_expected import VcMismatch, expected_vc, precheck_diff


@dataclass(frozen=True)
class VcCheckResult:
    module_name: str
    deep_text: str
    vc_text: str
    check_text: str
    root_text: str
    numbering: Numbering
    n_asserts: int
    mismatches: tuple[VcMismatch, ...]


def _program_errors(program: ast.Program) -> list[str]:
    errors: list[str] = []
    sites = [
        (b.label, i, len(b.commands))
        for b in program.blocks
        for i, c in enumerate(b.commands)
        if isinstance(c, ast.Assert)
    ]
    if not sites:
        errors.append("program has no assert; nothing to validate")
    elif len(sites) > 1:
        errors.append(
            f"program has {len(sites)} asserts; vc-check requires exactly "
            "one (run `ttac ua --strategy merge` first)"
        )
    elif sites[0][1] + 1 != sites[0][2]:
        errors.append(
            f"assert in block '{sites[0][0]}' is not the last command of "
            "its block"
        )

    idx = {b.label: i for i, b in enumerate(program.blocks)}
    for block in program.blocks:
        for succ in cfg.successors(block):
            if succ in idx and idx[succ] <= idx[block.label]:
                errors.append(
                    f"backward edge {block.label} -> {succ}: vc-check "
                    "requires blocks in topological source order"
                )

    if program.entry is not None:
        preds = cfg.predecessors(program).get(program.entry, [])
        if preds:
            errors.append(
                f"entry block '{program.entry}' has incoming edges "
                f"({', '.join(sorted(preds))})"
            )
        graph = cfg.to_digraph(program)
        import networkx as nx

        reachable = {program.entry} | nx.descendants(graph, program.entry)
        for block in program.blocks:
            if block.label not in reachable:
                errors.append(
                    f"block '{block.label}' is unreachable from entry"
                )
    return errors


def _vc_module(
    result_lines: list[str],
    module_name: str,
    numbering: Numbering,
    smt_source: str | None,
) -> str:
    n_blocks = len(numbering.block_index)
    block_map = ", ".join(
        f".blk {i} = {label}"
        for label, i in sorted(numbering.block_index.items(), key=lambda kv: kv[1])
    )
    lines = [
        emit._header(smt_source, tool="ttac vc-check"),
        "import Ttac",
        "",
        f"namespace {module_name}.Vc",
        "",
        "open Ttac",
        "",
        "/-!",
        f"guard atoms: {block_map}; .blk {n_blocks} = BLK_EXIT",
        "-/",
        "",
        "def vc : List BExp := [",
        *result_lines,
        "",
        f"end {module_name}.Vc",
        "",
    ]
    return "\n".join(lines)


def _check_module(module_name: str, kernel: bool) -> str:
    tactic = "decide" if kernel else "native_decide"
    trust = (
        "kernel-checked (`decide`)"
        if kernel
        else "proved by `native_decide` (trusts the Lean compiler via the "
        "`Lean.ofReduceBool` axiom)"
    )
    return "\n".join([
        f"/- Generated by `ttac vc-check`. DO NOT EDIT. `vc_ok` is {trust}. -/",
        f"import {module_name}.Deep",
        f"import {module_name}.Vc",
        "",
        f"namespace {module_name}",
        "",
        "/-- The transpiled smt2 asserts all belong to the constraint set the",
        "bwd0 encoder is entitled to emit for the deep program. -/",
        "theorem vc_ok : Ttac.checkVC Deep.prog Vc.vc = true := by",
        f"  {tactic}",
        "",
        "/-- The solver's `unsat` verdict on the smt2 file is `Ttac.Vc.Unsat",
        "Vc.vc` modulo the (goldens-tested) transpilation; under that premise",
        "the program is safe. Proved by the library's `checkVC_safe`. -/",
        "theorem vc_implies_safe : Ttac.Vc.Unsat Vc.vc → Deep.prog.Safe :=",
        "  Ttac.checkVC_safe vc_ok",
        "",
        f"end {module_name}",
        "",
    ])


def generate_vc_check(
    program: ast.Program,
    smt2_source: str,
    *,
    module_name: str,
    source: str | None = None,
    smt_source: str | None = None,
    precheck: bool = True,
    kernel: bool = False,
) -> VcCheckResult:
    pre = validate_for_lean(program)
    errors = list(pre.errors) + _program_errors(program)
    if errors:
        raise VcCheckError(tuple(errors))

    numbering = build_numbering(program, pre.types)

    smt = parse_smt2(smt2_source)
    syms, sym_errors = build_vc_symbols(program, numbering, pre.types, smt)
    asserts, transpile_errors = transpile_vc(smt, syms)
    smt_errors = sym_errors + transpile_errors
    if smt_errors:
        raise VcCheckError(tuple(smt_errors))

    mismatches: tuple[VcMismatch, ...] = ()
    if precheck:
        expected = expected_vc(program, numbering, pre.types)
        mismatches = precheck_diff(asserts, expected)

    vc_lines = _render_vc_entries(asserts)
    return VcCheckResult(
        module_name=module_name,
        deep_text=emit.deep_module(
            program, numbering, pre.types, module_name, source,
            tool="ttac vc-check",
        ),
        vc_text=_vc_module(vc_lines, module_name, numbering, smt_source),
        check_text=_check_module(module_name, kernel),
        root_text="\n".join([
            f"import {module_name}.Deep",
            f"import {module_name}.Vc",
            f"import {module_name}.Check",
            "",
        ]),
        numbering=numbering,
        n_asserts=len(asserts),
        mismatches=mismatches,
    )


def _render_vc_entries(asserts: list[VcAssert]) -> list[str]:
    lines: list[str] = []
    last = len(asserts) - 1
    for i, a in enumerate(asserts):
        lines.append(f"  -- line {a.line}: {a.source}")
        sep = "]" if i == last else ","
        lines.append(f"  {render_top(a.term)}{sep}")
    return lines
