"""Rule 6b (dehavoc window): orig carries a frontend-purified division
(havoc + Euclidean bounds via tacTmp chains), the rewriter recovered
the def via ``unpurify_div``. The walker pairs lhs-havoc with the
rhs def reached through a benign window and emits the uniqueness CHK.

The rw side is generated by actually running ``unpurify_div`` on the
orig, so the fixture tracks the real pass output shape.
"""

from __future__ import annotations

import shutil
import subprocess

import pytest

from ctac.ast.nodes import AssertCmd, AssignExpCmd
from ctac.parse import parse_string
from ctac.rewrite.unpurify_div import unpurify_div
from ctac.rw_eq import EquivContractError, emit_equivalence_program
from ctac.smt import build_vc, render_smt_script
from ctac.ua import split_asserts


def _z3_available() -> bool:
    return shutil.which("z3") is not None


def _wrap(body: str, *, syms: str) -> str:
    return f"""TACSymbolTable {{
\tUserDefined {{
\t}}
\tBuiltinFunctions {{
\t\tsafe_math_narrow_bv256:JSON{{"#class":"vc.data.TACBuiltInFunction.SafeMathNarrow.Implicit","returnSort":{{"bits":256}}}}
\t}}
\tUninterpretedFunctions {{
\t}}
\t{syms}
}}
Program {{
{body}
}}
Axioms {{
}}
Metas {{
  "0": []
}}
"""


# The frontend's "Division purification" shape: Q = A div B written
# as havoc + Euclidean bounds through tacTmp!div temps. A = 17, B = 5
# so the unique quotient is 3.
_PURIFIED = (
    "\tBlock e Succ [] {\n"
    "\t\tAssignExpCmd A 0x11\n"
    "\t\tAssignExpCmd B 0x5\n"
    "\t\tAssignHavocCmd Q\n"
    "\t\tAssignExpCmd tacTmp!div1!2 IntMul(Q B)\n"
    "\t\tAssignExpCmd tacTmp!div3!4 Le(tacTmp!div1!2 A)\n"
    '\t\tAssumeCmd tacTmp!div3!4 "Division purification"\n'
    "\t\tAssignExpCmd tacTmp!div5!6 IntAdd(Q 0x1)\n"
    "\t\tAssignExpCmd tacTmp!div7!8 IntMul(tacTmp!div5!6 B)\n"
    "\t\tAssignExpCmd tacTmp!div9!10 Gt(tacTmp!div7!8 A)\n"
    '\t\tAssumeCmd tacTmp!div9!10 "Division purification"\n'
    "\t\tAssignExpCmd ok Le(Q 0x3)\n"
    '\t\tAssertCmd ok "quotient bounded"\n'
    "\t}"
)

_SYMS = (
    "A:bv256\n\tB:bv256\n\tQ:bv256\n\tok:bool\n"
    "\ttacTmp!div1!2:bv256\n\ttacTmp!div3!4:bool\n\ttacTmp!div5!6:bv256\n"
    "\ttacTmp!div7!8:bv256\n\ttacTmp!div9!10:bool"
)


def _orig_and_rw():
    tac = parse_string(_wrap(_PURIFIED, syms=_SYMS), path="<s>")
    res = unpurify_div(tac.program)
    assert res.hits == 1, "fixture must trigger unpurify_div"
    return tac.program, res.program


def test_dehavoc_window_builds_and_emits_uniqueness_chk():
    orig, rw = _orig_and_rw()
    res = emit_equivalence_program(orig, rw)
    assert res.rule_hits.get("6b_dehavoc", 0) == 1
    # One rehavoc-site record carries the shadow name.
    sites = [s for s in res.rehavoc_sites if s.var_name == "Q"]
    assert len(sites) == 1 and sites[0].shadow_name.startswith("Q__rw_eq")
    # The shadow def is the recovered division.
    merged_assigns = {
        cmd.lhs: cmd
        for b in res.program.blocks
        for cmd in b.commands
        if isinstance(cmd, AssignExpCmd)
    }
    assert sites[0].shadow_name in merged_assigns


def test_dehavoc_rejected_under_strict():
    orig, rw = _orig_and_rw()
    with pytest.raises(EquivContractError, match="rule-6b dehavoc"):
        emit_equivalence_program(orig, rw, strict=True)


@pytest.mark.skipif(not _z3_available(), reason="z3 not on PATH")
def test_dehavoc_chks_discharge_via_z3():
    """Every CHK in the merged program (the Gt(B,0) admission and the
    uniqueness Eq(Q, shadow)) is implied by the Euclidean bounds —
    each split VC must be unsat."""
    from ctac.ir.models import TacFile

    orig, rw = _orig_and_rw()
    res = emit_equivalence_program(orig, rw)
    split = split_asserts(res.program)
    assert split.outputs, "expected at least one CHK split"
    for out in split.outputs:
        n_asserts = sum(
            isinstance(c, AssertCmd)
            for b in out.program.blocks
            for c in b.commands
        )
        assert n_asserts == 1
        vc = render_smt_script(
            build_vc(
                TacFile(
                    symbol_table_text="",
                    program=out.program,
                    axioms_text="",
                    metas={},
                ),
                encoding="sea_vc",
            )
        )
        proc = subprocess.run(
            ["z3", "-smt2", "-T:10", "-in"],
            input=vc, capture_output=True, text=True, timeout=30,
        )
        verdict = proc.stdout.strip().splitlines()[0]
        assert verdict == "unsat", f"assert #{out.index}: {verdict}\n{proc.stdout}"
