import Mathlib.Tactic.Linarith

/- Generated by `ttac lean` from nla_toassets_additivity.ttac. DO NOT EDIT. 
z3 on the generated VC: unsat, ~28ms (best of 5, z3 4.17.0).
-/

namespace Additivity.Shallow

/-!
Blocks in reverse topological order; each `ok_<label>` states
"execution from the top of <label> never fails an assert".
-/

def ok_entry : Prop :=
  ∀ (x : Int),
  ∀ (y : Int),
  ∀ (TA : Int),
  ∀ (TS : Int),
  (decide (0 ≤ x)) = true →
  (decide (0 ≤ y)) = true →
  (decide (0 ≤ TA)) = true →
  (decide (1 ≤ TS)) = true →
  let nx : Int := x * TA
  let ax : Int := Int.ediv nx TS
  let TA2 : Int := TA + ax
  let TS2 : Int := TS + x
  let ny : Int := y * TA2
  let ay : Int := Int.ediv ny TS2
  let sxy : Int := x + y
  let nxy : Int := sxy * TA
  let axy : Int := Int.ediv nxy TS
  let lhs : Int := ax + ay
  let ok : Bool := decide (lhs ≤ axy)
  ok = true ∧ True

end Additivity.Shallow

namespace Additivity

theorem shallow_safe : Shallow.ok_entry := by
  unfold Shallow.ok_entry
  simp only [decide_eq_true_eq, and_true]
  intro x y TA TS hx hy hTA hTS
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [bridge]
  have hTS' : (0 : Int) < TS := by omega
  rw [Int.le_ediv_iff_mul_le hTS']
  have f1 := Int.mul_ediv_add_emod (x * TA) TS
  have f1lo := Int.emod_nonneg (x * TA) (show TS ≠ 0 by omega)
  have f1hi := Int.emod_lt_of_pos (x * TA) hTS'
  have f2 := Int.mul_ediv_add_emod (y * (TA + x * TA / TS)) (TS + x)
  have f2lo := Int.emod_nonneg (y * (TA + x * TA / TS)) (show TS + x ≠ 0 by omega)
  have f2hi := Int.emod_lt_of_pos (y * (TA + x * TA / TS)) (show (0:Int) < TS + x by omega)
  nlinarith [f1, f1lo, f1hi, f2, f2lo, f2hi, hx, hy, hTA, hTS',
             mul_nonneg hx hTA, mul_nonneg hy hTA]

end Additivity
