/-
Shallow-embedding example: converted assets are capped (multi-block, nonlinear)

Emitted `namespace ConvertCap.Shallow` from `ttac lean` on
`docs/vc/examples/nla_convert_cap.ttac`; `shallow_safe` is hand-written.

z3 on the generated VC: unsat, ~9ms (best of 5, z3 4.17.0).
-/

/- Generated by `ttac lean` from nla_convert_cap.ttac. DO NOT EDIT. -/

namespace ConvertCap.Shallow

/-!
Blocks in reverse topological order; each `ok_<label>` states
"execution from the top of <label> never fails an assert".
-/

def ok_join (assets : Int) (total_assets : Int) : Prop :=
  let ok : Bool := decide (assets ≤ total_assets)
  ok = true ∧ True

def ok_prop (shares : Int) (total_assets : Int) (total_shares : Int) : Prop :=
  let raw : Int := total_assets * shares
  let assets_p : Int := Int.ediv raw total_shares
  ok_join assets_p total_assets

def ok_exact (total_assets : Int) : Prop :=
  let assets_e : Int := total_assets
  ok_join assets_e total_assets

def ok_entry : Prop :=
  ∀ (total_assets : Int),
  ∀ (total_shares : Int),
  ∀ (shares : Int),
  (decide (0 ≤ total_assets)) = true →
  (decide (1 ≤ total_shares)) = true →
  (decide (0 ≤ shares)) = true →
  (decide (shares ≤ total_shares)) = true →
  let is_exact : Bool := decide (shares = total_shares)
  (is_exact = true → ok_exact total_assets) ∧ (is_exact = false → ok_prop shares total_assets total_shares)

end ConvertCap.Shallow

namespace ConvertCap

/-- Multi-block: the assert follows the exact/proportional branch through a
    phi. The `exact` arm is trivial (`omega`); the `prop` arm needs the div
    upper bound `floor(TA*shares/TS) <= TA` from `shares <= TS` and `TA >= 0`
    (`ediv_le_iff_le_mul` + one `mul_le_mul`). Core Lean. -/
theorem shallow_safe : Shallow.ok_entry := by
  unfold Shallow.ok_entry Shallow.ok_exact Shallow.ok_prop Shallow.ok_join
  simp only [decide_eq_true_eq, decide_eq_false_iff_not, and_true]
  intro total_assets total_shares shares hTA hTS _ hsh
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [bridge]
  refine ⟨fun _ => by omega, fun _ => ?_⟩
  rw [Int.ediv_le_iff_le_mul (show (0 : Int) < total_shares by omega)]
  have hmul : total_assets * shares ≤ total_assets * total_shares :=
    Int.mul_le_mul_of_nonneg_left hsh (by omega)
  omega

end ConvertCap
