/-
Shallow-embedding example: fee-waterfall solvency (LARGE: 34 blocks)

Emitted `namespace FeeWaterfall.Shallow` from `ttac lean` on
`docs/vc/examples/nla_fee_waterfall.ttac`; proofs hand-written.
A value passes through 8 stages; each takes a waivable proportional
floor mul-div fee (a branch+phi diamond). Safety `0 <= v_final` is
proved by a bottom-up per-stage lemma, so the proof is LINEAR in the
number of stages -- it does not explode as 2^8 over the branches.

z3 on the generated VC: unsat, ~345ms (best of 5, z3 4.17.0).
-/

/- Generated by `ttac lean` from nla_fee_waterfall.ttac. DO NOT EDIT. -/

namespace FeeWaterfall.Shallow

/-!
Blocks in reverse topological order; each `ok_<label>` states
"execution from the top of <label> never fails an assert".
-/

def ok_done (v8 : Int) : Prop :=
  let ok : Bool := decide (0 ≤ v8)
  ok = true ∧ True

def ok_merge8 (eff8 : Int) (v7 : Int) : Prop :=
  let v8 : Int := v7 - eff8
  ok_done v8

def ok_waived8 (v7 : Int) : Prop :=
  let effw8 : Int := 0
  ok_merge8 effw8 v7

def ok_charged8 (fee8 : Int) (v7 : Int) : Prop :=
  let effc8 : Int := fee8
  ok_merge8 effc8 v7

def ok_stage8 (rate8 : Int) (scale : Int) (v7 : Int) (waive8 : Bool) : Prop :=
  let raw8 : Int := v7 * rate8
  let fee8 : Int := Int.ediv raw8 scale
  (waive8 = true → ok_waived8 v7) ∧ (waive8 = false → ok_charged8 fee8 v7)

def ok_merge7 (eff7 : Int) (rate8 : Int) (scale : Int) (v6 : Int) (waive8 : Bool) : Prop :=
  let v7 : Int := v6 - eff7
  ok_stage8 rate8 scale v7 waive8

def ok_waived7 (rate8 : Int) (scale : Int) (v6 : Int) (waive8 : Bool) : Prop :=
  let effw7 : Int := 0
  ok_merge7 effw7 rate8 scale v6 waive8

def ok_charged7 (fee7 : Int) (rate8 : Int) (scale : Int) (v6 : Int) (waive8 : Bool) : Prop :=
  let effc7 : Int := fee7
  ok_merge7 effc7 rate8 scale v6 waive8

def ok_stage7 (rate7 : Int) (rate8 : Int) (scale : Int) (v6 : Int) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let raw7 : Int := v6 * rate7
  let fee7 : Int := Int.ediv raw7 scale
  (waive7 = true → ok_waived7 rate8 scale v6 waive8) ∧ (waive7 = false → ok_charged7 fee7 rate8 scale v6 waive8)

def ok_merge6 (eff6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v5 : Int) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let v6 : Int := v5 - eff6
  ok_stage7 rate7 rate8 scale v6 waive7 waive8

def ok_waived6 (rate7 : Int) (rate8 : Int) (scale : Int) (v5 : Int) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let effw6 : Int := 0
  ok_merge6 effw6 rate7 rate8 scale v5 waive7 waive8

def ok_charged6 (fee6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v5 : Int) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let effc6 : Int := fee6
  ok_merge6 effc6 rate7 rate8 scale v5 waive7 waive8

def ok_stage6 (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v5 : Int) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let raw6 : Int := v5 * rate6
  let fee6 : Int := Int.ediv raw6 scale
  (waive6 = true → ok_waived6 rate7 rate8 scale v5 waive7 waive8) ∧ (waive6 = false → ok_charged6 fee6 rate7 rate8 scale v5 waive7 waive8)

def ok_merge5 (eff5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v4 : Int) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let v5 : Int := v4 - eff5
  ok_stage6 rate6 rate7 rate8 scale v5 waive6 waive7 waive8

def ok_waived5 (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v4 : Int) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let effw5 : Int := 0
  ok_merge5 effw5 rate6 rate7 rate8 scale v4 waive6 waive7 waive8

def ok_charged5 (fee5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v4 : Int) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let effc5 : Int := fee5
  ok_merge5 effc5 rate6 rate7 rate8 scale v4 waive6 waive7 waive8

def ok_stage5 (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v4 : Int) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let raw5 : Int := v4 * rate5
  let fee5 : Int := Int.ediv raw5 scale
  (waive5 = true → ok_waived5 rate6 rate7 rate8 scale v4 waive6 waive7 waive8) ∧ (waive5 = false → ok_charged5 fee5 rate6 rate7 rate8 scale v4 waive6 waive7 waive8)

def ok_merge4 (eff4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v3 : Int) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let v4 : Int := v3 - eff4
  ok_stage5 rate5 rate6 rate7 rate8 scale v4 waive5 waive6 waive7 waive8

def ok_waived4 (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v3 : Int) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let effw4 : Int := 0
  ok_merge4 effw4 rate5 rate6 rate7 rate8 scale v3 waive5 waive6 waive7 waive8

def ok_charged4 (fee4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v3 : Int) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let effc4 : Int := fee4
  ok_merge4 effc4 rate5 rate6 rate7 rate8 scale v3 waive5 waive6 waive7 waive8

def ok_stage4 (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v3 : Int) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let raw4 : Int := v3 * rate4
  let fee4 : Int := Int.ediv raw4 scale
  (waive4 = true → ok_waived4 rate5 rate6 rate7 rate8 scale v3 waive5 waive6 waive7 waive8) ∧ (waive4 = false → ok_charged4 fee4 rate5 rate6 rate7 rate8 scale v3 waive5 waive6 waive7 waive8)

def ok_merge3 (eff3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v2 : Int) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let v3 : Int := v2 - eff3
  ok_stage4 rate4 rate5 rate6 rate7 rate8 scale v3 waive4 waive5 waive6 waive7 waive8

def ok_waived3 (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v2 : Int) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let effw3 : Int := 0
  ok_merge3 effw3 rate4 rate5 rate6 rate7 rate8 scale v2 waive4 waive5 waive6 waive7 waive8

def ok_charged3 (fee3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v2 : Int) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let effc3 : Int := fee3
  ok_merge3 effc3 rate4 rate5 rate6 rate7 rate8 scale v2 waive4 waive5 waive6 waive7 waive8

def ok_stage3 (rate3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v2 : Int) (waive3 : Bool) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let raw3 : Int := v2 * rate3
  let fee3 : Int := Int.ediv raw3 scale
  (waive3 = true → ok_waived3 rate4 rate5 rate6 rate7 rate8 scale v2 waive4 waive5 waive6 waive7 waive8) ∧ (waive3 = false → ok_charged3 fee3 rate4 rate5 rate6 rate7 rate8 scale v2 waive4 waive5 waive6 waive7 waive8)

def ok_merge2 (eff2 : Int) (rate3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v1 : Int) (waive3 : Bool) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let v2 : Int := v1 - eff2
  ok_stage3 rate3 rate4 rate5 rate6 rate7 rate8 scale v2 waive3 waive4 waive5 waive6 waive7 waive8

def ok_waived2 (rate3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v1 : Int) (waive3 : Bool) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let effw2 : Int := 0
  ok_merge2 effw2 rate3 rate4 rate5 rate6 rate7 rate8 scale v1 waive3 waive4 waive5 waive6 waive7 waive8

def ok_charged2 (fee2 : Int) (rate3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v1 : Int) (waive3 : Bool) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let effc2 : Int := fee2
  ok_merge2 effc2 rate3 rate4 rate5 rate6 rate7 rate8 scale v1 waive3 waive4 waive5 waive6 waive7 waive8

def ok_stage2 (rate2 : Int) (rate3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v1 : Int) (waive2 : Bool) (waive3 : Bool) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let raw2 : Int := v1 * rate2
  let fee2 : Int := Int.ediv raw2 scale
  (waive2 = true → ok_waived2 rate3 rate4 rate5 rate6 rate7 rate8 scale v1 waive3 waive4 waive5 waive6 waive7 waive8) ∧ (waive2 = false → ok_charged2 fee2 rate3 rate4 rate5 rate6 rate7 rate8 scale v1 waive3 waive4 waive5 waive6 waive7 waive8)

def ok_merge1 (eff1 : Int) (rate2 : Int) (rate3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v0 : Int) (waive2 : Bool) (waive3 : Bool) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let v1 : Int := v0 - eff1
  ok_stage2 rate2 rate3 rate4 rate5 rate6 rate7 rate8 scale v1 waive2 waive3 waive4 waive5 waive6 waive7 waive8

def ok_waived1 (rate2 : Int) (rate3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v0 : Int) (waive2 : Bool) (waive3 : Bool) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let effw1 : Int := 0
  ok_merge1 effw1 rate2 rate3 rate4 rate5 rate6 rate7 rate8 scale v0 waive2 waive3 waive4 waive5 waive6 waive7 waive8

def ok_charged1 (fee1 : Int) (rate2 : Int) (rate3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v0 : Int) (waive2 : Bool) (waive3 : Bool) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let effc1 : Int := fee1
  ok_merge1 effc1 rate2 rate3 rate4 rate5 rate6 rate7 rate8 scale v0 waive2 waive3 waive4 waive5 waive6 waive7 waive8

def ok_stage1 (rate1 : Int) (rate2 : Int) (rate3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v0 : Int) (waive1 : Bool) (waive2 : Bool) (waive3 : Bool) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) : Prop :=
  let raw1 : Int := v0 * rate1
  let fee1 : Int := Int.ediv raw1 scale
  (waive1 = true → ok_waived1 rate2 rate3 rate4 rate5 rate6 rate7 rate8 scale v0 waive2 waive3 waive4 waive5 waive6 waive7 waive8) ∧ (waive1 = false → ok_charged1 fee1 rate2 rate3 rate4 rate5 rate6 rate7 rate8 scale v0 waive2 waive3 waive4 waive5 waive6 waive7 waive8)

def ok_entry : Prop :=
  ∀ (scale : Int),
  ∀ (v0 : Int),
  (decide (1 ≤ scale)) = true →
  (decide (0 ≤ v0)) = true →
  ∀ (rate1 : Int),
  (decide (0 ≤ rate1)) = true →
  (decide (rate1 ≤ scale)) = true →
  ∀ (waive1 : Bool),
  ∀ (rate2 : Int),
  (decide (0 ≤ rate2)) = true →
  (decide (rate2 ≤ scale)) = true →
  ∀ (waive2 : Bool),
  ∀ (rate3 : Int),
  (decide (0 ≤ rate3)) = true →
  (decide (rate3 ≤ scale)) = true →
  ∀ (waive3 : Bool),
  ∀ (rate4 : Int),
  (decide (0 ≤ rate4)) = true →
  (decide (rate4 ≤ scale)) = true →
  ∀ (waive4 : Bool),
  ∀ (rate5 : Int),
  (decide (0 ≤ rate5)) = true →
  (decide (rate5 ≤ scale)) = true →
  ∀ (waive5 : Bool),
  ∀ (rate6 : Int),
  (decide (0 ≤ rate6)) = true →
  (decide (rate6 ≤ scale)) = true →
  ∀ (waive6 : Bool),
  ∀ (rate7 : Int),
  (decide (0 ≤ rate7)) = true →
  (decide (rate7 ≤ scale)) = true →
  ∀ (waive7 : Bool),
  ∀ (rate8 : Int),
  (decide (0 ≤ rate8)) = true →
  (decide (rate8 ≤ scale)) = true →
  ∀ (waive8 : Bool),
  ok_stage1 rate1 rate2 rate3 rate4 rate5 rate6 rate7 rate8 scale v0 waive1 waive2 waive3 waive4 waive5 waive6 waive7 waive8

end FeeWaterfall.Shallow

namespace FeeWaterfall

theorem safe_stage8 (rate8 : Int) (scale : Int) (v : Int) (waive8 : Bool) (hs : 0 < scale) (hv : 0 ≤ v) (hlo8 : 0 ≤ rate8) (hhi8 : rate8 ≤ scale) :
    Shallow.ok_stage8 rate8 scale v waive8 := by
  unfold Shallow.ok_stage8 Shallow.ok_waived8 Shallow.ok_charged8 Shallow.ok_merge8 Shallow.ok_done
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [decide_eq_true_eq, and_true, bridge]
  have hfl : 0 ≤ v * rate8 / scale := Int.ediv_nonneg (Int.mul_nonneg hv hlo8) (by omega)
  have hfh : v * rate8 / scale ≤ v := by
    rw [Int.ediv_le_iff_le_mul hs]
    have := Int.mul_le_mul_of_nonneg_left hhi8 hv
    omega
  exact ⟨fun _ => by omega, fun _ => by omega⟩

theorem safe_stage7 (rate7 : Int) (rate8 : Int) (scale : Int) (v : Int) (waive7 : Bool) (waive8 : Bool) (hs : 0 < scale) (hv : 0 ≤ v) (hlo7 : 0 ≤ rate7) (hhi7 : rate7 ≤ scale) (hlo8 : 0 ≤ rate8) (hhi8 : rate8 ≤ scale) :
    Shallow.ok_stage7 rate7 rate8 scale v waive7 waive8 := by
  unfold Shallow.ok_stage7 Shallow.ok_waived7 Shallow.ok_charged7 Shallow.ok_merge7
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [bridge]
  have hfl : 0 ≤ v * rate7 / scale := Int.ediv_nonneg (Int.mul_nonneg hv hlo7) (by omega)
  have hfh : v * rate7 / scale ≤ v := by
    rw [Int.ediv_le_iff_le_mul hs]
    have := Int.mul_le_mul_of_nonneg_left hhi7 hv
    omega
  exact ⟨fun _ => safe_stage8 rate8 scale _ waive8 hs (by omega) hlo8 hhi8, fun _ => safe_stage8 rate8 scale _ waive8 hs (by omega) hlo8 hhi8⟩

theorem safe_stage6 (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v : Int) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) (hs : 0 < scale) (hv : 0 ≤ v) (hlo6 : 0 ≤ rate6) (hhi6 : rate6 ≤ scale) (hlo7 : 0 ≤ rate7) (hhi7 : rate7 ≤ scale) (hlo8 : 0 ≤ rate8) (hhi8 : rate8 ≤ scale) :
    Shallow.ok_stage6 rate6 rate7 rate8 scale v waive6 waive7 waive8 := by
  unfold Shallow.ok_stage6 Shallow.ok_waived6 Shallow.ok_charged6 Shallow.ok_merge6
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [bridge]
  have hfl : 0 ≤ v * rate6 / scale := Int.ediv_nonneg (Int.mul_nonneg hv hlo6) (by omega)
  have hfh : v * rate6 / scale ≤ v := by
    rw [Int.ediv_le_iff_le_mul hs]
    have := Int.mul_le_mul_of_nonneg_left hhi6 hv
    omega
  exact ⟨fun _ => safe_stage7 rate7 rate8 scale _ waive7 waive8 hs (by omega) hlo7 hhi7 hlo8 hhi8, fun _ => safe_stage7 rate7 rate8 scale _ waive7 waive8 hs (by omega) hlo7 hhi7 hlo8 hhi8⟩

theorem safe_stage5 (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v : Int) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) (hs : 0 < scale) (hv : 0 ≤ v) (hlo5 : 0 ≤ rate5) (hhi5 : rate5 ≤ scale) (hlo6 : 0 ≤ rate6) (hhi6 : rate6 ≤ scale) (hlo7 : 0 ≤ rate7) (hhi7 : rate7 ≤ scale) (hlo8 : 0 ≤ rate8) (hhi8 : rate8 ≤ scale) :
    Shallow.ok_stage5 rate5 rate6 rate7 rate8 scale v waive5 waive6 waive7 waive8 := by
  unfold Shallow.ok_stage5 Shallow.ok_waived5 Shallow.ok_charged5 Shallow.ok_merge5
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [bridge]
  have hfl : 0 ≤ v * rate5 / scale := Int.ediv_nonneg (Int.mul_nonneg hv hlo5) (by omega)
  have hfh : v * rate5 / scale ≤ v := by
    rw [Int.ediv_le_iff_le_mul hs]
    have := Int.mul_le_mul_of_nonneg_left hhi5 hv
    omega
  exact ⟨fun _ => safe_stage6 rate6 rate7 rate8 scale _ waive6 waive7 waive8 hs (by omega) hlo6 hhi6 hlo7 hhi7 hlo8 hhi8, fun _ => safe_stage6 rate6 rate7 rate8 scale _ waive6 waive7 waive8 hs (by omega) hlo6 hhi6 hlo7 hhi7 hlo8 hhi8⟩

theorem safe_stage4 (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v : Int) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) (hs : 0 < scale) (hv : 0 ≤ v) (hlo4 : 0 ≤ rate4) (hhi4 : rate4 ≤ scale) (hlo5 : 0 ≤ rate5) (hhi5 : rate5 ≤ scale) (hlo6 : 0 ≤ rate6) (hhi6 : rate6 ≤ scale) (hlo7 : 0 ≤ rate7) (hhi7 : rate7 ≤ scale) (hlo8 : 0 ≤ rate8) (hhi8 : rate8 ≤ scale) :
    Shallow.ok_stage4 rate4 rate5 rate6 rate7 rate8 scale v waive4 waive5 waive6 waive7 waive8 := by
  unfold Shallow.ok_stage4 Shallow.ok_waived4 Shallow.ok_charged4 Shallow.ok_merge4
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [bridge]
  have hfl : 0 ≤ v * rate4 / scale := Int.ediv_nonneg (Int.mul_nonneg hv hlo4) (by omega)
  have hfh : v * rate4 / scale ≤ v := by
    rw [Int.ediv_le_iff_le_mul hs]
    have := Int.mul_le_mul_of_nonneg_left hhi4 hv
    omega
  exact ⟨fun _ => safe_stage5 rate5 rate6 rate7 rate8 scale _ waive5 waive6 waive7 waive8 hs (by omega) hlo5 hhi5 hlo6 hhi6 hlo7 hhi7 hlo8 hhi8, fun _ => safe_stage5 rate5 rate6 rate7 rate8 scale _ waive5 waive6 waive7 waive8 hs (by omega) hlo5 hhi5 hlo6 hhi6 hlo7 hhi7 hlo8 hhi8⟩

theorem safe_stage3 (rate3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v : Int) (waive3 : Bool) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) (hs : 0 < scale) (hv : 0 ≤ v) (hlo3 : 0 ≤ rate3) (hhi3 : rate3 ≤ scale) (hlo4 : 0 ≤ rate4) (hhi4 : rate4 ≤ scale) (hlo5 : 0 ≤ rate5) (hhi5 : rate5 ≤ scale) (hlo6 : 0 ≤ rate6) (hhi6 : rate6 ≤ scale) (hlo7 : 0 ≤ rate7) (hhi7 : rate7 ≤ scale) (hlo8 : 0 ≤ rate8) (hhi8 : rate8 ≤ scale) :
    Shallow.ok_stage3 rate3 rate4 rate5 rate6 rate7 rate8 scale v waive3 waive4 waive5 waive6 waive7 waive8 := by
  unfold Shallow.ok_stage3 Shallow.ok_waived3 Shallow.ok_charged3 Shallow.ok_merge3
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [bridge]
  have hfl : 0 ≤ v * rate3 / scale := Int.ediv_nonneg (Int.mul_nonneg hv hlo3) (by omega)
  have hfh : v * rate3 / scale ≤ v := by
    rw [Int.ediv_le_iff_le_mul hs]
    have := Int.mul_le_mul_of_nonneg_left hhi3 hv
    omega
  exact ⟨fun _ => safe_stage4 rate4 rate5 rate6 rate7 rate8 scale _ waive4 waive5 waive6 waive7 waive8 hs (by omega) hlo4 hhi4 hlo5 hhi5 hlo6 hhi6 hlo7 hhi7 hlo8 hhi8, fun _ => safe_stage4 rate4 rate5 rate6 rate7 rate8 scale _ waive4 waive5 waive6 waive7 waive8 hs (by omega) hlo4 hhi4 hlo5 hhi5 hlo6 hhi6 hlo7 hhi7 hlo8 hhi8⟩

theorem safe_stage2 (rate2 : Int) (rate3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v : Int) (waive2 : Bool) (waive3 : Bool) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) (hs : 0 < scale) (hv : 0 ≤ v) (hlo2 : 0 ≤ rate2) (hhi2 : rate2 ≤ scale) (hlo3 : 0 ≤ rate3) (hhi3 : rate3 ≤ scale) (hlo4 : 0 ≤ rate4) (hhi4 : rate4 ≤ scale) (hlo5 : 0 ≤ rate5) (hhi5 : rate5 ≤ scale) (hlo6 : 0 ≤ rate6) (hhi6 : rate6 ≤ scale) (hlo7 : 0 ≤ rate7) (hhi7 : rate7 ≤ scale) (hlo8 : 0 ≤ rate8) (hhi8 : rate8 ≤ scale) :
    Shallow.ok_stage2 rate2 rate3 rate4 rate5 rate6 rate7 rate8 scale v waive2 waive3 waive4 waive5 waive6 waive7 waive8 := by
  unfold Shallow.ok_stage2 Shallow.ok_waived2 Shallow.ok_charged2 Shallow.ok_merge2
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [bridge]
  have hfl : 0 ≤ v * rate2 / scale := Int.ediv_nonneg (Int.mul_nonneg hv hlo2) (by omega)
  have hfh : v * rate2 / scale ≤ v := by
    rw [Int.ediv_le_iff_le_mul hs]
    have := Int.mul_le_mul_of_nonneg_left hhi2 hv
    omega
  exact ⟨fun _ => safe_stage3 rate3 rate4 rate5 rate6 rate7 rate8 scale _ waive3 waive4 waive5 waive6 waive7 waive8 hs (by omega) hlo3 hhi3 hlo4 hhi4 hlo5 hhi5 hlo6 hhi6 hlo7 hhi7 hlo8 hhi8, fun _ => safe_stage3 rate3 rate4 rate5 rate6 rate7 rate8 scale _ waive3 waive4 waive5 waive6 waive7 waive8 hs (by omega) hlo3 hhi3 hlo4 hhi4 hlo5 hhi5 hlo6 hhi6 hlo7 hhi7 hlo8 hhi8⟩

theorem safe_stage1 (rate1 : Int) (rate2 : Int) (rate3 : Int) (rate4 : Int) (rate5 : Int) (rate6 : Int) (rate7 : Int) (rate8 : Int) (scale : Int) (v : Int) (waive1 : Bool) (waive2 : Bool) (waive3 : Bool) (waive4 : Bool) (waive5 : Bool) (waive6 : Bool) (waive7 : Bool) (waive8 : Bool) (hs : 0 < scale) (hv : 0 ≤ v) (hlo1 : 0 ≤ rate1) (hhi1 : rate1 ≤ scale) (hlo2 : 0 ≤ rate2) (hhi2 : rate2 ≤ scale) (hlo3 : 0 ≤ rate3) (hhi3 : rate3 ≤ scale) (hlo4 : 0 ≤ rate4) (hhi4 : rate4 ≤ scale) (hlo5 : 0 ≤ rate5) (hhi5 : rate5 ≤ scale) (hlo6 : 0 ≤ rate6) (hhi6 : rate6 ≤ scale) (hlo7 : 0 ≤ rate7) (hhi7 : rate7 ≤ scale) (hlo8 : 0 ≤ rate8) (hhi8 : rate8 ≤ scale) :
    Shallow.ok_stage1 rate1 rate2 rate3 rate4 rate5 rate6 rate7 rate8 scale v waive1 waive2 waive3 waive4 waive5 waive6 waive7 waive8 := by
  unfold Shallow.ok_stage1 Shallow.ok_waived1 Shallow.ok_charged1 Shallow.ok_merge1
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [bridge]
  have hfl : 0 ≤ v * rate1 / scale := Int.ediv_nonneg (Int.mul_nonneg hv hlo1) (by omega)
  have hfh : v * rate1 / scale ≤ v := by
    rw [Int.ediv_le_iff_le_mul hs]
    have := Int.mul_le_mul_of_nonneg_left hhi1 hv
    omega
  exact ⟨fun _ => safe_stage2 rate2 rate3 rate4 rate5 rate6 rate7 rate8 scale _ waive2 waive3 waive4 waive5 waive6 waive7 waive8 hs (by omega) hlo2 hhi2 hlo3 hhi3 hlo4 hhi4 hlo5 hhi5 hlo6 hhi6 hlo7 hhi7 hlo8 hhi8, fun _ => safe_stage2 rate2 rate3 rate4 rate5 rate6 rate7 rate8 scale _ waive2 waive3 waive4 waive5 waive6 waive7 waive8 hs (by omega) hlo2 hhi2 hlo3 hhi3 hlo4 hhi4 hlo5 hhi5 hlo6 hhi6 hlo7 hhi7 hlo8 hhi8⟩

theorem shallow_safe : Shallow.ok_entry := by
  unfold Shallow.ok_entry
  simp only [decide_eq_true_eq]
  intro scale v0 hs0 hv0 rate1 hlo1 hhi1 waive1 rate2 hlo2 hhi2 waive2 rate3 hlo3 hhi3 waive3 rate4 hlo4 hhi4 waive4 rate5 hlo5 hhi5 waive5 rate6 hlo6 hhi6 waive6 rate7 hlo7 hhi7 waive7 rate8 hlo8 hhi8 waive8
  exact safe_stage1 rate1 rate2 rate3 rate4 rate5 rate6 rate7 rate8 scale v0 waive1 waive2 waive3 waive4 waive5 waive6 waive7 waive8 (by omega) hv0 hlo1 hhi1 hlo2 hhi2 hlo3 hhi3 hlo4 hhi4 hlo5 hhi5 hlo6 hhi6 hlo7 hhi7 hlo8 hhi8

end FeeWaterfall
