/-
Shallow-embedding example: floor mul-div monotone in the numerator (nonlinear)

Emitted `namespace Monotone.Shallow` block below is from `ttac lean` on
`docs/vc/examples/nla_muldiv_monotone.ttac`; the `shallow_safe` theorem is hand-written.
See docs/vc/examples/README.md.

z3 on the generated VC: unsat, ~8ms (best of 5, z3 4.17.0).
-/

/- Generated by `ttac lean` from nla_muldiv_monotone.ttac. DO NOT EDIT. -/

namespace Monotone.Shallow

/-!
Blocks in reverse topological order; each `ok_<label>` states
"execution from the top of <label> never fails an assert".
-/

def ok_entry : Prop :=
  ∀ (sa : Int),
  ∀ (sb : Int),
  ∀ (p : Int),
  ∀ (q : Int),
  (decide (sa ≤ sb)) = true →
  (decide (0 ≤ p)) = true →
  (decide (1 ≤ q)) = true →
  let na : Int := sa * p
  let nb : Int := sb * p
  let fa : Int := Int.ediv na q
  let fb : Int := Int.ediv nb q
  let ok : Bool := decide (fa ≤ fb)
  ok = true ∧ True

end Monotone.Shallow

namespace Monotone

/-- `sa <= sb, 0 <= p, 1 <= q  =>  floor(sa*p/q) <= floor(sb*p/q)`.
    `sa*p <= sb*p` (mul by nonneg), then `ediv` monotone in the numerator.
    Two core lemmas, no `omega` case work. -/
theorem shallow_safe : Shallow.ok_entry := by
  unfold Shallow.ok_entry
  simp only [decide_eq_true_eq, and_true]
  intro sa sb p q hsab hp hq
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [bridge]
  exact Int.ediv_le_ediv (by omega) (Int.mul_le_mul_of_nonneg_right hsab (by omega))

end Monotone
