/-
Nested-shallow variant of ConvertCap ("SSA is functional programming").

Emitted `namespace ConvertCapNested.Shallow` from `ttac lean --nested`
on `docs/vc/examples/nla_convert_cap.ttac`; proof hand-written. Blocks
are `let rec` defs nested under their immediate dominator, so the flat
form's threaded live-in (`ok_join` took `assets` PLUS `total_assets`)
is captured lexically and `ok_join`'s only parameter is its phi target.
-/

/- Generated by `ttac lean` from nla_convert_cap.ttac. DO NOT EDIT. -/

namespace ConvertCapNested.Shallow

/-!
Blocks nested by immediate dominator (`let rec`); parameters are
phi targets only - live-ins are captured lexically. Each
`ok_<label>` states "execution from the top of <label> never
fails an assert".
-/

def ok_entry : Prop :=
  ∀ (total_assets : Int),
  ∀ (total_shares : Int),
  ∀ (shares : Int),
  (decide (0 ≤ total_assets)) = true →
  (decide (1 ≤ total_shares)) = true →
  (decide (0 ≤ shares)) = true →
  (decide (shares ≤ total_shares)) = true →
  let is_exact : Bool := decide (shares = total_shares)
  let rec ok_join (assets : Int) : Prop :=
    let ok : Bool := decide (assets ≤ total_assets)
    ok = true ∧ True
  let rec ok_prop : Prop :=
    let raw : Int := total_assets * shares
    let assets_p : Int := Int.ediv raw total_shares
    ok_join assets_p
  let rec ok_exact : Prop :=
    let assets_e : Int := total_assets
    ok_join assets_e
  (is_exact = true → ok_exact) ∧ (is_exact = false → ok_prop)

end ConvertCapNested.Shallow

namespace ConvertCapNested

/-- Same proof shape as the flat ConvertCap.shallow_safe; the lifted
    `let rec` constants replace the top-level block defs. -/
theorem shallow_safe : Shallow.ok_entry := by
  unfold Shallow.ok_entry Shallow.ok_entry.ok_exact Shallow.ok_entry.ok_prop
    Shallow.ok_entry.ok_join
  simp only [decide_eq_true_eq, decide_eq_false_iff_not, and_true]
  intro total_assets total_shares shares hTA hTS _ hsh
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [bridge]
  refine ⟨fun _ => by omega, fun _ => ?_⟩
  rw [Int.ediv_le_iff_le_mul (show (0 : Int) < total_shares by omega)]
  have hmul : total_assets * shares ≤ total_assets * total_shares :=
    Int.mul_le_mul_of_nonneg_left hsh (by omega)
  omega

end ConvertCapNested
