/-
Nested-shallow variant of ShareBurnU (chain of four branch/phi diamonds).

Emitted `namespace ShareBurnUNested.Shallow` from `ttac lean --nested`
on `docs/vc/examples/nla_share_burn_unguarded.ttac`; proofs
hand-written. Each join takes exactly its phi target (1 param); every
other block takes none (flat form: up to 5 threaded params). The
structural point: the folded-merge-lemma pattern survives -- the flat
proof's `join_b_mono`, stated over the FOLDED `ok_join_b` and applied
at all four branch leaves, restates against the lifted nested constant
`ok_entry.ok_join_a.ok_join_b`, whose capture args (user_balance,
assets_a) are fully generic in the constant signature.
-/

/- Generated by `ttac lean` from nla_share_burn_unguarded.ttac. DO NOT EDIT. -/

namespace ShareBurnUNested.Shallow

/-!
Blocks nested by immediate dominator (`let rec`); parameters are
phi targets only - live-ins are captured lexically. Each
`ok_<label>` states "execution from the top of <label> never
fails an assert".
-/

def ok_entry : Prop :=
  ∀ (total_assets : Int),
  ∀ (total_shares : Int),
  ∀ (shares_a : Int),
  ∀ (shares_b : Int),
  ∀ (user_balance : Int),
  (decide (1 ≤ total_assets)) = true →
  (decide (1 ≤ total_shares)) = true →
  (decide (shares_a < shares_b)) = true →
  (decide (shares_b ≤ total_shares)) = true →
  let is_exact_a : Bool := decide (shares_a = total_shares)
  let rec ok_join_a (assets_a : Int) : Prop :=
    let is_exact_b : Bool := decide (shares_b = total_shares)
    let rec ok_join_b (assets_b : Int) : Prop :=
      let cap_a_left : Bool := decide (user_balance < assets_a)
      let rec ok_join_cap_a (burn_a : Int) : Prop :=
        let cap_b_left : Bool := decide (user_balance < assets_b)
        let rec ok_join_cap_b (burn_b : Int) : Prop :=
          let ok : Bool := decide (burn_a ≤ burn_b)
          ok = true ∧ True
        let rec ok_cap_b_user : Prop :=
          let burn_b_cap_b_user : Int := user_balance
          ok_join_cap_b burn_b_cap_b_user
        let rec ok_cap_b_assets : Prop :=
          let burn_b_cap_b_assets : Int := assets_b
          ok_join_cap_b burn_b_cap_b_assets
        (cap_b_left = true → ok_cap_b_user) ∧ (cap_b_left = false → ok_cap_b_assets)
      let rec ok_cap_a_user : Prop :=
        let burn_a_cap_a_user : Int := user_balance
        ok_join_cap_a burn_a_cap_a_user
      let rec ok_cap_a_assets : Prop :=
        let burn_a_cap_a_assets : Int := assets_a
        ok_join_cap_a burn_a_cap_a_assets
      (cap_a_left = true → ok_cap_a_user) ∧ (cap_a_left = false → ok_cap_a_assets)
    let rec ok_proportional_b : Prop :=
      let assets_b_raw : Int := total_assets * shares_b
      let assets_b_proportional_b : Int := Int.ediv assets_b_raw total_shares
      ok_join_b assets_b_proportional_b
    let rec ok_exact_b : Prop :=
      let assets_b_exact_b : Int := total_assets
      ok_join_b assets_b_exact_b
    (is_exact_b = true → ok_exact_b) ∧ (is_exact_b = false → ok_proportional_b)
  let rec ok_proportional_a : Prop :=
    let assets_a_raw : Int := total_assets * shares_a
    let assets_a_proportional_a : Int := Int.ediv assets_a_raw total_shares
    ok_join_a assets_a_proportional_a
  let rec ok_exact_a : Prop :=
    let assets_a_exact_a : Int := total_assets
    ok_join_a assets_a_exact_a
  (is_exact_a = true → ok_exact_a) ∧ (is_exact_a = false → ok_proportional_a)

end ShareBurnUNested.Shallow

namespace ShareBurnUNested

/-- Same folded-merge lemma as the flat `ShareBurnU.join_b_mono`; the
    lifted constant's capture args (user_balance, assets_a) precede the
    phi param (assets_b), all fully generic. Pure linear `omega`. -/
theorem join_b_mono (user_balance assets_a assets_b : Int)
    (h : assets_a ≤ assets_b) :
    Shallow.ok_entry.ok_join_a.ok_join_b user_balance assets_a assets_b := by
  unfold Shallow.ok_entry.ok_join_a.ok_join_b
    Shallow.ok_entry.ok_join_a.ok_join_b.ok_cap_a_user
    Shallow.ok_entry.ok_join_a.ok_join_b.ok_cap_a_assets
    Shallow.ok_entry.ok_join_a.ok_join_b.ok_join_cap_a
    Shallow.ok_entry.ok_join_a.ok_join_b.ok_join_cap_a.ok_cap_b_user
    Shallow.ok_entry.ok_join_a.ok_join_b.ok_join_cap_a.ok_cap_b_assets
    Shallow.ok_entry.ok_join_a.ok_join_b.ok_join_cap_a.ok_join_cap_b
  simp only [decide_eq_true_eq, decide_eq_false_iff_not, and_true]
  omega

theorem shallow_safe : Shallow.ok_entry := by
  unfold Shallow.ok_entry Shallow.ok_entry.ok_exact_a
    Shallow.ok_entry.ok_proportional_a Shallow.ok_entry.ok_join_a
    Shallow.ok_entry.ok_join_a.ok_exact_b
    Shallow.ok_entry.ok_join_a.ok_proportional_b
  simp only [decide_eq_true_eq, decide_eq_false_iff_not]
  intro total_assets total_shares shares_a shares_b user_balance hTA hTS hsab hsbTS
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [bridge]
  have hTS' : (0 : Int) < total_shares := by omega
  refine ⟨fun hea => ⟨fun _ => ?_, fun _ => ?_⟩, fun _ => ⟨fun _ => ?_, fun _ => ?_⟩⟩
  · -- exact_a, exact_b: assets_a = assets_b = total_assets
    exact join_b_mono _ _ _ (by omega)
  · -- exact_a, proportional_b: infeasible (shares_a = total_shares < shares_b <= total_shares)
    exact absurd hea (by omega)
  · -- proportional_a, exact_b: floor(TA*shares_a/TS) <= TA  (div upper bound)
    refine join_b_mono _ _ _ ?_
    rw [Int.ediv_le_iff_le_mul hTS']
    have := Int.mul_le_mul_of_nonneg_left (show shares_a ≤ total_shares by omega)
      (show (0 : Int) ≤ total_assets by omega)
    omega
  · -- proportional_a, proportional_b: floor(TA*sa/TS) <= floor(TA*sb/TS)  (div monotone)
    refine join_b_mono _ _ _ ?_
    exact Int.ediv_le_ediv hTS'
      (Int.mul_le_mul_of_nonneg_left (by omega) (show (0 : Int) ≤ total_assets by omega))

end ShareBurnUNested
