/-
Shallow-embedding example: floor/ceil mul-div round-trip (nonlinear; needs div lemmas)

The `namespace Roundtrip.Shallow` block below is emitted by `ttac lean` from
`docs/vc/examples/nla_muldiv_roundtrip.ttac` (regenerate with:
`ttac lean docs/vc/examples/nla_muldiv_roundtrip.ttac -o <dir> --no-deep --name Roundtrip`).
The `theorem shallow_safe` at the bottom is the hand-written proof that
the assertion is never violated. See docs/vc/examples/README.md.

z3 on the generated VC: unsat, ~10ms (best of 5, z3 4.17.0).
-/

/- Generated by `ttac lean` from nla_muldiv_roundtrip.ttac. DO NOT EDIT. -/

namespace Roundtrip.Shallow

/-!
Blocks in reverse topological order; each `ok_<label>` states
"execution from the top of <label> never fails an assert".
-/

def ok_entry : Prop :=
  ∀ (a : Int),
  ∀ (b : Int),
  ∀ (c : Int),
  (decide (0 ≤ a)) = true →
  (decide (1 ≤ b)) = true →
  (decide (1 ≤ c)) = true →
  let ab : Int := a * b
  let q : Int := Int.ediv ab c
  let qc : Int := q * c
  let num : Int := qc + b
  let num1 : Int := num - 1
  let r : Int := Int.ediv num1 b
  let ok : Bool := decide (r ≤ a)
  ok = true ∧ True

end Roundtrip.Shallow

namespace Roundtrip

/-- Unlike the guarded examples, no `assume` hands over the ordering:
    the proof must derive `q*c <= a*b` (floor lower bound) and discharge
    the outer ceil-div via `Int.ediv_le_iff_le_mul`. `omega` alone FAILS
    here (it abstracts the nested `ediv`). All lemmas are core Lean. -/
theorem shallow_safe : Shallow.ok_entry := by
  unfold Shallow.ok_entry
  simp only [decide_eq_true_eq, and_true]
  intro a b c ha hb hc
  -- the emitter writes `Int.ediv`; core div lemmas are stated with `/` (= ediv on Int)
  have bridge : ∀ x y : Int, x.ediv y = x / y := fun _ _ => rfl
  simp only [bridge]
  have hb' : (0 : Int) < b := by omega
  rw [Int.ediv_le_iff_le_mul hb']
  have key : a * b / c * c ≤ a * b := by
    have h := Int.mul_ediv_add_emod (a * b) c
    have hnn := Int.emod_nonneg (a * b) (show c ≠ 0 by omega)
    have hcomm : c * (a * b / c) = a * b / c * c := Int.mul_comm c _
    omega
  omega

end Roundtrip
