/-
Shallow-embedding example: share/burn min-cap monotonicity (guarded; omega one-shot)

The `namespace ShareBurn.Shallow` block below is emitted by `ttac lean` from
`docs/vc/examples/practical_share_burn_monotonicity.ttac` (regenerate with:
`ttac lean docs/vc/examples/practical_share_burn_monotonicity.ttac -o <dir> --no-deep --name ShareBurn`).
The `theorem shallow_safe` at the bottom is the hand-written proof that
the assertion is never violated. See docs/vc/examples/README.md.

z3 on the generated VC: unsat, ~6ms (best of 5, z3 4.17.0).
-/

/- Generated by `ttac lean` from practical_share_burn_monotonicity.ttac. DO NOT EDIT. -/

namespace ShareBurn.Shallow

/-!
Blocks in reverse topological order; each `ok_<label>` states
"execution from the top of <label> never fails an assert".
-/

def ok_join_cap_b (burn_a : Int) (burn_b : Int) : Prop :=
  let ok : Bool := decide (burn_a ≤ burn_b)
  ok = true ∧ True

def ok_cap_b_user (burn_a : Int) (user_balance : Int) : Prop :=
  let burn_b_cap_b_user : Int := user_balance
  ok_join_cap_b burn_a burn_b_cap_b_user

def ok_cap_b_assets (assets_b : Int) (burn_a : Int) : Prop :=
  let burn_b_cap_b_assets : Int := assets_b
  ok_join_cap_b burn_a burn_b_cap_b_assets

def ok_join_cap_a (assets_b : Int) (burn_a : Int) (user_balance : Int) : Prop :=
  let cap_b_left : Bool := decide (user_balance < assets_b)
  (cap_b_left = true → ok_cap_b_user burn_a user_balance) ∧ (cap_b_left = false → ok_cap_b_assets assets_b burn_a)

def ok_cap_a_user (assets_b : Int) (user_balance : Int) : Prop :=
  let burn_a_cap_a_user : Int := user_balance
  ok_join_cap_a assets_b burn_a_cap_a_user user_balance

def ok_cap_a_assets (assets_a : Int) (assets_b : Int) (user_balance : Int) : Prop :=
  let burn_a_cap_a_assets : Int := assets_a
  ok_join_cap_a assets_b burn_a_cap_a_assets user_balance

def ok_join_b (assets_a : Int) (assets_b : Int) (user_balance : Int) : Prop :=
  (decide (assets_a ≤ assets_b)) = true →
  let cap_a_left : Bool := decide (user_balance < assets_a)
  (cap_a_left = true → ok_cap_a_user assets_b user_balance) ∧ (cap_a_left = false → ok_cap_a_assets assets_a assets_b user_balance)

def ok_proportional_b (assets_a : Int) (shares_b : Int) (total_assets : Int) (total_shares : Int) (user_balance : Int) : Prop :=
  let assets_b_raw : Int := total_assets * shares_b
  let assets_b_proportional_b : Int := Int.ediv assets_b_raw total_shares
  ok_join_b assets_a assets_b_proportional_b user_balance

def ok_exact_b (assets_a : Int) (total_assets : Int) (user_balance : Int) : Prop :=
  let assets_b_exact_b : Int := total_assets
  ok_join_b assets_a assets_b_exact_b user_balance

def ok_join_a (assets_a : Int) (shares_b : Int) (total_assets : Int) (total_shares : Int) (user_balance : Int) : Prop :=
  let is_exact_b : Bool := decide (shares_b = total_shares)
  (is_exact_b = true → ok_exact_b assets_a total_assets user_balance) ∧ (is_exact_b = false → ok_proportional_b assets_a shares_b total_assets total_shares user_balance)

def ok_proportional_a (shares_a : Int) (shares_b : Int) (total_assets : Int) (total_shares : Int) (user_balance : Int) : Prop :=
  let assets_a_raw : Int := total_assets * shares_a
  let assets_a_proportional_a : Int := Int.ediv assets_a_raw total_shares
  ok_join_a assets_a_proportional_a shares_b total_assets total_shares user_balance

def ok_exact_a (shares_b : Int) (total_assets : Int) (total_shares : Int) (user_balance : Int) : Prop :=
  let assets_a_exact_a : Int := total_assets
  ok_join_a assets_a_exact_a shares_b total_assets total_shares user_balance

def ok_entry : Prop :=
  ∀ (total_assets : Int),
  ∀ (total_shares : Int),
  ∀ (shares_a : Int),
  ∀ (shares_b : Int),
  ∀ (user_balance : Int),
  (decide (1 ≤ total_assets)) = true →
  (decide (1 ≤ total_shares)) = true →
  (decide (shares_a < shares_b)) = true →
  (decide (shares_b ≤ total_shares)) = true →
  let is_exact_a : Bool := decide (shares_a = total_shares)
  (is_exact_a = true → ok_exact_a shares_b total_assets total_shares user_balance) ∧ (is_exact_a = false → ok_proportional_a shares_a shares_b total_assets total_shares user_balance)

end ShareBurn.Shallow

namespace ShareBurn

/-- Safety of the whole program. Every nonlinear `mul`/`ediv` result is
    consumed only under the `assume assets_a <= assets_b` guard, so the
    obligation collapses to min-cap monotonicity over linear atoms and
    `omega` closes it after the boolean skeleton is reduced. -/
theorem shallow_safe : Shallow.ok_entry := by
  unfold Shallow.ok_entry Shallow.ok_exact_a Shallow.ok_proportional_a Shallow.ok_join_a
    Shallow.ok_exact_b Shallow.ok_proportional_b Shallow.ok_join_b
    Shallow.ok_cap_a_user Shallow.ok_cap_a_assets Shallow.ok_join_cap_a
    Shallow.ok_cap_b_user Shallow.ok_cap_b_assets Shallow.ok_join_cap_b
  simp only [decide_eq_true_eq, decide_eq_false_iff_not, and_true]
  omega

end ShareBurn
