/-
Shallow-embedding example: same-denominator floor mul-div superadditivity (nonlinear)

Emitted `namespace Superadd.Shallow` block below is from `ttac lean` on
`docs/vc/examples/nla_muldiv_superadd.ttac`; the `shallow_safe` theorem is hand-written.
See docs/vc/examples/README.md.

z3 on the generated VC: unsat, ~9ms (best of 5, z3 4.17.0).
-/

/- Generated by `ttac lean` from nla_muldiv_superadd.ttac. DO NOT EDIT. -/

namespace Superadd.Shallow

/-!
Blocks in reverse topological order; each `ok_<label>` states
"execution from the top of <label> never fails an assert".
-/

def ok_entry : Prop :=
  ∀ (x : Int),
  ∀ (y : Int),
  ∀ (p : Int),
  ∀ (q : Int),
  (decide (0 ≤ x)) = true →
  (decide (0 ≤ y)) = true →
  (decide (0 ≤ p)) = true →
  (decide (1 ≤ q)) = true →
  let nx : Int := x * p
  let ny : Int := y * p
  let fx : Int := Int.ediv nx q
  let fy : Int := Int.ediv ny q
  let sxy : Int := x + y
  let nxy : Int := sxy * p
  let fxy : Int := Int.ediv nxy q
  let lhs : Int := fx + fy
  let ok : Bool := decide (lhs ≤ fxy)
  ok = true ∧ True

end Superadd.Shallow

namespace Superadd

/-- `floor(x*p/q) + floor(y*p/q) <= floor((x+y)*p/q)`.  Reduce the outer div
    with `le_ediv_iff_mul_le`, feed the two floor lower bounds, let `omega`
    glue the linear residue (products aligned by `mul_comm`/`add_mul`). -/
theorem shallow_safe : Shallow.ok_entry := by
  unfold Shallow.ok_entry
  simp only [decide_eq_true_eq, and_true]
  intro x y p q hx hy hp hq
  have bridge : ∀ a b : Int, a.ediv b = a / b := fun _ _ => rfl
  simp only [bridge]
  have hq' : (0 : Int) < q := by omega
  rw [Int.le_ediv_iff_mul_le hq']
  have bx := Int.mul_ediv_add_emod (x * p) q
  have byy := Int.mul_ediv_add_emod (y * p) q
  have hnx := Int.emod_nonneg (x * p) (show q ≠ 0 by omega)
  have hny := Int.emod_nonneg (y * p) (show q ≠ 0 by omega)
  have hdist : (x + y) * p = x * p + y * p := Int.add_mul x y p
  have e1 : (x * p / q) * q = q * (x * p / q) := Int.mul_comm _ _
  have e2 : (y * p / q) * q = q * (y * p / q) := Int.mul_comm _ _
  have hc : (x * p / q + y * p / q) * q = (x * p / q) * q + (y * p / q) * q :=
    Int.add_mul _ _ _
  omega

end Superadd
