/-
Shallow-embedding example: withdrawal summary bounds (guarded; omega one-shot)

The `namespace Withdrawal.Shallow` block below is emitted by `ttac lean` from
`docs/vc/examples/practical_withdrawal_summary.ttac` (regenerate with:
`ttac lean docs/vc/examples/practical_withdrawal_summary.ttac -o <dir> --no-deep --name Withdrawal`).
The `theorem shallow_safe` at the bottom is the hand-written proof that
the assertion is never violated. See docs/vc/examples/README.md.

z3 on the generated VC: unsat, ~6ms (best of 5, z3 4.17.0).
-/

/- Generated by `ttac lean` from practical_withdrawal_summary.ttac. DO NOT EDIT. -/

namespace Withdrawal.Shallow

/-!
Blocks in reverse topological order; each `ok_<label>` states
"execution from the top of <label> never fails an assert".
-/

def ok_assert_block (available_cash : Int) (request : Int) (withdraw_amount : Int) : Prop :=
  let ok_request : Bool := decide (withdraw_amount ≤ request)
  let ok_cash : Bool := decide (withdraw_amount ≤ available_cash)
  let ok : Bool := ok_request && ok_cash
  ok = true ∧ True

def ok_cap_request (available_cash : Int) (request : Int) : Prop :=
  let withdraw_amount_cap_request : Int := request
  ok_assert_block available_cash request withdraw_amount_cap_request

def ok_cap_available (available_cash : Int) (candidate : Int) (request : Int) : Prop :=
  let withdraw_amount_cap_available : Int := candidate
  ok_assert_block available_cash request withdraw_amount_cap_available

def ok_candidate_join (available_cash : Int) (candidate : Int) (request : Int) : Prop :=
  let request_is_smaller : Bool := decide (request < candidate)
  (request_is_smaller = true → ok_cap_request available_cash request) ∧ (request_is_smaller = false → ok_cap_available available_cash candidate request)

def ok_withdraw_mode (available_cash : Int) (request : Int) : Prop :=
  let candidate_withdraw_mode : Int := available_cash
  ok_candidate_join available_cash candidate_withdraw_mode request

def ok_repay_mode (available_cash : Int) (priced_value : Int) (request : Int) : Prop :=
  let candidate_repay_mode : Int := priced_value
  ok_candidate_join available_cash candidate_repay_mode request

def ok_rate_join (available_cash : Int) (deposit_shares : Int) (mode : Int) (price : Int) (rate : Int) (request : Int) (total_deposit_shares : Int) : Prop :=
  let share_value_raw : Int := available_cash * deposit_shares
  let share_value : Int := Int.ediv share_value_raw total_deposit_shares
  let priced_value : Int := Int.ediv (share_value * price) rate
  (decide (priced_value ≤ available_cash)) = true →
  let is_repay_mode : Bool := decide (mode = 1)
  (is_repay_mode = true → ok_repay_mode available_cash priced_value request) ∧ (is_repay_mode = false → ok_withdraw_mode available_cash request)

def ok_elevated_rate (available_cash : Int) (deposit_shares : Int) (mode : Int) (price : Int) (request : Int) (total_deposit_shares : Int) : Prop :=
  let rate_elevated_rate : Int := 150
  ok_rate_join available_cash deposit_shares mode price rate_elevated_rate request total_deposit_shares

def ok_base_rate (available_cash : Int) (deposit_shares : Int) (mode : Int) (price : Int) (request : Int) (total_deposit_shares : Int) : Prop :=
  let rate_base_rate : Int := 100
  ok_rate_join available_cash deposit_shares mode price rate_base_rate request total_deposit_shares

def ok_entry : Prop :=
  ∀ (liquidity : Int),
  ∀ (debt_before : Int),
  ∀ (reserves : Int),
  ∀ (deposit_shares : Int),
  ∀ (total_deposit_shares : Int),
  ∀ (request : Int),
  ∀ (price : Int),
  ∀ (mode : Int),
  (decide (debt_before ≤ liquidity)) = true →
  let liquid_after_debt : Int := liquidity - debt_before
  (decide (reserves ≤ liquid_after_debt)) = true →
  let available_cash : Int := liquid_after_debt - reserves
  (decide (1 ≤ total_deposit_shares)) = true →
  (decide (deposit_shares ≤ total_deposit_shares)) = true →
  (decide (1 ≤ request)) = true →
  (decide (1 ≤ price)) = true →
  ((decide (mode = 1)) || (decide (mode = 2))) = true →
  let old_util : Int := Int.ediv (debt_before * 100) liquidity
  let hypothetical_debt : Int := debt_before + request
  let new_util : Int := Int.ediv (hypothetical_debt * 100) liquidity
  let utilization_rises : Bool := decide (old_util < new_util)
  (utilization_rises = true → ok_elevated_rate available_cash deposit_shares mode price request total_deposit_shares) ∧ (utilization_rises = false → ok_base_rate available_cash deposit_shares mode price request total_deposit_shares)

end Withdrawal.Shallow

namespace Withdrawal

/-- Same shape as ShareBurn: the `assume priced_value <= available_cash`
    guard plus the min-caps make the goal linear after abstraction. The
    assert here is a `Bool` conjunction, so `Bool.and_eq_true` is added. -/
theorem shallow_safe : Shallow.ok_entry := by
  unfold Shallow.ok_entry Shallow.ok_base_rate Shallow.ok_elevated_rate Shallow.ok_rate_join
    Shallow.ok_repay_mode Shallow.ok_withdraw_mode Shallow.ok_candidate_join
    Shallow.ok_cap_request Shallow.ok_cap_available Shallow.ok_assert_block
  simp only [decide_eq_true_eq, decide_eq_false_iff_not, and_true, Bool.and_eq_true]
  omega

end Withdrawal
